import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync,symlinkSync,linkSync} from 'node:fs';import {tmpdir} from 'node:os';import{join}from'node:path';
import{buildStockSelection,evaluatedInputs,cli}from'./build-stock-selection.mjs';
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'stock-capture-pure-')),repo=join(root,'repo'),proof=join(repo,'tests/Broker.NativeProof'),policy=join(proof,'Policy');mkdirSync(policy,{recursive:true});mkdirSync(join(repo,'.config'));writeFileSync(join(repo,'.config/dotnet-tools.json'),JSON.stringify({tools:{fable:{version:'5.18.0'}}}));
 for(const file of ['Directory.Build.props','StockSelection.fs','StockSelection.fsproj','StockSelection.packages.lock.json','build-stock-selection.mjs'])writeFileSync(join(policy,file),'source');for(const file of ['package.json','package-lock.json'])writeFileSync(join(proof,file),'{}');
 mkdirSync(join(proof,'node_modules/@fable-org/fable-library-js'),{recursive:true});writeFileSync(join(proof,'node_modules/@fable-org/fable-library-js/Array.js'),'runtime');const reference=join(repo,'Fable.Core.dll');writeFileSync(reference,'mock-reference-bytes');
 const capture=join(root,'capture'),calls=[];
 const run=(executable,argv,options)=>{
  calls.push({executable,argv,options});if(argv[0]==='restore')return{status:0,stdout:Buffer.from('restore\r\n'),stderr:Buffer.from([0,1,2])};const output=argv[argv.indexOf('--outDir')+1];mkdirSync(join(output,'fable_modules/fable-library-js.5.18.0'),{recursive:true});writeFileSync(join(output,'fable_modules/fable-library-js.5.18.0/Array.js'),'runtime');writeFileSync(join(output,'StockSelection.js'),'import { x } from "./fable_modules/fable-library-js.5.18.0/Array.js";\n');
  return{status:0,stdout:Buffer.from(`F# PROJECT: tests/Broker.NativeProof/Policy/StockSelection.fsproj\nFABLE LIBRARY: ${output}/fable_modules\nTARGET FRAMEWORK: net10.0\nOUTPUT TYPE: Library\n\n    -r:${reference}\n    ${policy}/StockSelection.fs\n\n`),stderr:Buffer.from('compiler-warning\n')};
 };
 return{root,repo,proof,policy,capture,calls,run,reference};
}
function using(body){const f=fixture();try{body(f)}finally{rmSync(f.root,{recursive:true,force:true})}}
const read=(f,n)=>JSON.parse(readFileSync(join(f.capture,n),'utf8'));
test('real production capture retains raw streams, argv/env, evaluated graph and rewrite',()=>using(f=>{
 const descriptor=buildStockSelection({policyRoot:f.policy,captureDir:f.capture,environment:{PATH:'/mock/no-launch',HOME:'/unchanged',TOKEN:'secret'}},f.run);assert.equal(f.calls.length,2);assert.ok(f.calls[1].argv.includes('--verbose'));assert.equal(f.calls[1].options.env.HOME,'/unchanged');assert.equal(f.calls[1].options.env.TOKEN,undefined);assert.equal(f.calls[1].options.env.TMPDIR,join(f.capture,'tmp'));
 assert.deepEqual(readFileSync(join(f.capture,'restore.stderr.raw')),Buffer.from([0,1,2]));assert.equal(read(f,'fable.json').cwd,f.repo);assert.equal(read(f,'evaluated-inputs.json').sources.length,1);assert.equal(read(f,'evaluated-inputs.json').references.length,1);assert.equal(read(f,'result.json').captureComplete,true);assert.ok(existsSync(join(f.capture,'fable-output/StockSelection.js')));assert.equal(read(f,'rewrite-correspondence.json').rewritten.sha256,descriptor.output.sha256);
}));
test('restore error retains exact raw failure and no new descriptor',()=>using(f=>{const mock=()=>({status:1,stdout:Buffer.from('out'),stderr:Buffer.from('fail')});assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},mock),/restore failed/);assert.equal(read(f,'result.json').captureComplete,false);assert.equal(read(f,'result.json').publishedNewDescriptor,false);assert.equal(readFileSync(join(f.capture,'restore.stderr.raw'),'utf8'),'fail');assert.equal(existsSync(join(f.policy,'generated/stock-selection-policy.json')),false)}));
test('signal/timeout records refusal and partial compiler graph retained',()=>using(f=>{const mock=(...args)=>{const x=f.run(...args);return args[1][0]==='fable'?{...x,status:null,signal:'SIGTERM',error:{code:'ETIMEDOUT',message:'timeout'}}:x};assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},mock),/fable failed/);assert.equal(read(f,'fable.json').signal,'SIGTERM');assert.equal(read(f,'fable.json').error.code,'ETIMEDOUT');assert.ok(read(f,'retained-graph.json').length>0);assert.equal(read(f,'result.json').captureComplete,false)}));
test('capture collision refuses before mock launches',()=>using(f=>{mkdirSync(f.capture);assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},f.run),/fresh/);assert.equal(f.calls.length,0)}));
test('capture parent symlink refuses before mock launches',()=>using(f=>{const actual=join(f.root,'actual');mkdirSync(actual);symlinkSync(actual,join(f.root,'link'));assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:join(f.root,'link/capture')},f.run),/symlink/);assert.equal(f.calls.length,0)}));
test('runtime hash mismatch fails without publication',()=>using(f=>{writeFileSync(join(f.proof,'node_modules/@fable-org/fable-library-js/Array.js'),'foreign');assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},f.run),/differs/);assert.equal(read(f,'result.json').publishedNewDescriptor,false)}));
test('temporary graph symlink fails with retained custody failure',()=>using(f=>{const mock=(...args)=>{const x=f.run(...args);if(args[1][0]==='fable')symlinkSync(f.reference,join(f.capture,'fable-output/foreign'));return x};assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},mock),/symlink/);assert.equal(read(f,'result.json').captureComplete,false);assert.match(read(f,'result.json').graphCustodyFailure,/symlink/)}));
test('temporary graph hardlink fails',()=>using(f=>{const mock=(...args)=>{const x=f.run(...args);if(args[1][0]==='fable')linkSync(f.reference,join(f.capture,'fable-output/foreign'));return x};assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},mock),/single-link/);assert.equal(read(f,'result.json').captureComplete,false)}));
test('missing actual verbose graph cannot publish descriptor',()=>using(f=>{const mock=(...args)=>({...f.run(...args),stdout:Buffer.from('no graph')});assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},mock),/verbose/);assert.equal(read(f,'result.json').publishedNewDescriptor,false)}));
test('authored drift during compiler run fails',()=>using(f=>{const mock=(...args)=>{const x=f.run(...args);if(args[1][0]==='fable')writeFileSync(join(f.policy,'StockSelection.fs'),'changed');return x};assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},mock),/drift/);assert.equal(read(f,'result.json').captureComplete,false)}));
test('old descriptor remains explicitly historical on compiler failure',()=>using(f=>{mkdirSync(join(f.policy,'generated'));writeFileSync(join(f.policy,'generated/stock-selection-policy.json'),'old');assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture},()=>({status:1,stdout:'',stderr:'error'})),/restore failed/);assert.equal(read(f,'result.json').originalDescriptor.bytes,3);assert.equal(read(f,'result.json').publishedNewDescriptor,false);assert.equal(readFileSync(join(f.policy,'generated/stock-selection-policy.json'),'utf8'),'old')}));
test('untyped graph and missing references fail',()=>{assert.throws(()=>evaluatedInputs(Buffer.from('F# PROJECT: p\nFABLE LIBRARY: f\nTARGET FRAMEWORK: t\nOUTPUT TYPE: o\n\n    bad\n'),'/'),/source\/reference/)});
test('unknown CLI options refuse before production build',()=>assert.throws(()=>cli(['--foreign']),/usage|CLI/));

test('explicit config is the actual nested restore argument and byte-pinned before/after',()=>using(f=>{const config=join(f.root,'stock.NuGet.Config');writeFileSync(config,'<configuration><packageSources><clear /></packageSources></configuration>');buildStockSelection({policyRoot:f.policy,captureDir:f.capture,nugetConfig:config},f.run);assert.deepEqual(f.calls[0].argv.slice(-2),['--configfile',config]);assert.deepEqual(read(f,'nuget-config-before.json'),read(f,'nuget-config-after.json'));assert.equal(f.calls[0].options.maxBuffer,1048576)}));
test('explicit config drift refuses descriptor publication',()=>using(f=>{const config=join(f.root,'stock.NuGet.Config');writeFileSync(config,'original');const mock=(...args)=>{const x=f.run(...args);if(args[1][0]==='fable')writeFileSync(config,'changed');return x};assert.throws(()=>buildStockSelection({policyRoot:f.policy,captureDir:f.capture,nugetConfig:config},mock),/config drift/);assert.equal(read(f,'result.json').publishedNewDescriptor,false)}));
test('wrong config path/type/link refuses before nested launch',()=>using(f=>{for(const config of ['relative',join(f.root,'absent'),f.root]){assert.throws(()=>buildStockSelection({policyRoot:f.policy,nugetConfig:config},f.run));assert.equal(f.calls.length,0)}const config=join(f.root,'linked');symlinkSync(f.reference,config);assert.throws(()=>buildStockSelection({policyRoot:f.policy,nugetConfig:config},f.run),/regular/);assert.equal(f.calls.length,0)}));
test('explicit duplicate config CLI is refused',()=>assert.throws(()=>cli(['--nuget-config','/a','--nuget-config','/b']),/CLI/));
