<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
    <NuGetLockFilePath>StockSelection.Tests.packages.lock.json</NuGetLockFilePath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="StockSelection.Tests.fs" />
    <ProjectReference Include="StockSelection.fsproj" />
    <PackageReference Include="Fable.Core" Version="[5.3.0]" />
  </ItemGroup>
</Project>
