import assert from"node:assert/strict";import{verifyJourneyEvidence,validateHandoff}from"./live-native-evidence.mjs";
const actor={id:"17",lifetime:"9007199254740993"},attack={id:"29",lifetime:"9007199254740995",health:100},targets={replace:{x:10,z:11},append:{x:12,z:13},stop:{x:30,z:30}};
const j={id:"local-pointer",mode:"pointer",actor,attack,targets,tolerance:.5,maxStoppedDisplacement:.5};
const gids=["00112233-4455-6677-8899-aabbccdde001","00112233-4455-6677-8899-aabbccdde002","00112233-4455-6677-8899-aabbccdde003","00112233-4455-6677-8899-aabbccdde004","00112233-4455-6677-8899-aabbccdde005"];
function b64(g){const p=g.split("-"),hex=(p[0].match(/../g).reverse().join("")+p[1].match(/../g).reverse().join("")+p[2].match(/../g).reverse().join("")+p[3]+p[4]);return Buffer.from(hex,"hex").toString("base64")}
const actions=[{kind:"Move",policy:"MOVE_POLICY_REPLACE",target:targets.replace},{kind:"Move",policy:"MOVE_POLICY_APPEND",target:targets.append},{kind:"Move",policy:"MOVE_POLICY_REPLACE",target:targets.stop},{kind:"Stop"},{kind:"Attack",targetActor:attack}];
const moduleSha256="a".repeat(64),controller={sessionId:"AQEBAQEBAQEBAQEBAQEBAQ==",controllerId:"AgICAgICAgICAgICAgICAg==",controllerIncarnation:"controller-1",authorityEpoch:"1"},basis={token:"AwMDAwMDAwMDAwMDAwMDAw==",stateSequence:"1",nativeFrame:1,matchId:"BAQEBAQEBAQEBAQEBAQEBA==",processIncarnation:"p",stateChannelIncarnation:"s"};
const browser=actions.map((action,i)=>({schema:"fsbar.barc-live-browser-submit/v1",journeyId:j.id,parentId:b64(gids[i]),inputId:b64(gids[i]),moduleSha256,moduleGeneration:"1",controller,basis,actor,action}));
const host=[];for(let i=0;i<5;i++)for(const[stage,status]of[["BrokerAdmission","Accepted"],["NativeAdmission","Accepted"],["NativeDispatch","Applied"]])host.push({kind:"result",parentId:gids[i],inputId:gids[i],moduleGeneration:"1",authorityEpoch:"1",commandChannelIncarnation:"channel-1",actorId:17,actorLifetime:actor.lifetime,stage,status,nativeFrame:(i+1)*10,wireEnvelope:JSON.stringify({result:{parentId:b64(gids[i]),inputId:b64(gids[i]),module:{sha256:Buffer.from(moduleSha256,"hex").toString("base64"),generation:"1"},controller,basis}})});
host.push({kind:"observation",units:[{id:"17",health:100},{id:"29",health:100}]},{kind:"observation",units:[{id:"17",health:100},{id:"29",health:90}]});
const cmd=(target)=>({id:10,coded:0,target});const engine=[{frame:20,actorId:"17",actorPosition:{x:9,z:10},actorCommands:[cmd(targets.replace),cmd(targets.append)],targetId:"29",targetHealth:100},{frame:25,actorId:"17",actorPosition:targets.replace,actorCommands:[cmd(targets.append)],targetId:"29",targetHealth:100},{frame:30,actorId:"17",actorPosition:targets.append,actorCommands:[],targetId:"29",targetHealth:100},{frame:35,actorId:"17",actorPosition:{x:14,z:14},actorCommands:[cmd(targets.stop)],targetId:"29",targetHealth:100},{frame:41,actorId:"17",actorPosition:{x:15,z:15},actorCommands:[],targetId:"29",targetHealth:100},{frame:45,actorId:"17",actorPosition:{x:15.1,z:15.1},actorCommands:[],targetId:"29",targetHealth:100},{frame:51,actorId:"17",actorPosition:{x:15.1,z:15.1},actorCommands:[{id:20}],targetId:"29",targetHealth:100},{frame:55,actorId:"17",actorPosition:{x:15.1,z:15.1},actorCommands:[{id:20}],targetId:"29",targetHealth:90}];
assert.equal(verifyJourneyEvidence(j,browser,host,engine),true);assert.throws(()=>verifyJourneyEvidence(j,browser,host.filter(x=>x.stage!=="NativeAdmission"),engine),/NativeAdmission/);
const product=id=>({id,qualificationPath:"/q",journeys:["pointer","keyboard","custom"].map(mode=>{
  const base={id:`${id}-${mode}`,mode,receiverUrl:"http://127.0.0.1:1/barc/?barc-profile=barc-live-v1",allowedOrigin:"http://127.0.0.1:1",gatewayUrl:"ws://127.0.0.1:2/live",credential:`c-${id}-${mode}`,actor,nativeTracePath:"/n",engineTracePath:"/e"};
  if(mode==="custom")return{...base,custom:{guestPath:"/g",guestSha256:"a".repeat(64),inputControl:"Move",nativeKind:"Move",target:{x:1,z:2},inputPolicy:"MOVE_POLICY_APPEND",policy:"MOVE_POLICY_REPLACE"}};
  return{...base,targets,attack,...(mode==="keyboard"?{keys:{replace:["ArrowRight"],append:["ArrowUp"],stop:["ArrowLeft"]}}:{})};
})});
const handoff={schema:"fsbar.barc-live-native-browser-handoff/v1",nativeHostSchema:"fsbar.barc-native-live-host/v1",sourceCommit:"a".repeat(40),archiveSha256:"b".repeat(64),clientSha256:"c".repeat(64),fixtureMode:false,products:[product("local"),product("generated")]};assert.equal(validateHandoff(handoff),handoff);assert.throws(()=>validateHandoff({...handoff,fixtureMode:true}),/forbidden/);console.log("live native raw evidence contract test: passed");
