<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PreviewTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Broker.Browser.Preview\Broker.Browser.Preview.fsproj" />
    <ProjectReference Include="..\..\src\Broker.Browser.Contracts\Broker.Browser.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Expecto" Version="10.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" Version="0.15.3" />
  </ItemGroup>
</Project>
