import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { canonicalObject, encodeObject, v1 } from "../../src/Broker.Browser.Contracts/generated/codec.js";
import { assertStockQueueEvidence } from "./tactical-native-evidence.mjs";
import { computeStockRevision, joinStockFinalRead, materializeStockHandoff, normalizeFrozenStockEvidence, normalizeStockSample, parseClosedJson, parseStockTraceJsonl, validateStockSmokeHandoff, validateStockTraceRecord } from "./stock-native-trace.mjs";

const request="BARC_QUEUE_REQUEST/1\nlength=00000101\nbridge=barc-stock-queue-reader-v1\ndomain=production\nunit=42\nend\n";
const response="BARC_QUEUE_RESPONSE/1\nlength=00000244\nbridge=barc-stock-queue-reader-v1\nrequest-sha256=b01b44c1eaea587730eae794c0b87e4e05dddecfb508abd295ac1e138a0f5960\nstatus=ok\ndomain=production\nunit=42\ncount=1\nrow=production|-710|32|41|3f800000,80000000\nend\n";
const catalogueId=Buffer.from(Array.from({length:16},(_,index)=>index)).toString("base64"),matchId=Buffer.from(Array.from({length:16},(_,index)=>index+16)).toString("base64");
const context=()=>({profile:"barc-live-tactical-stock-v1",tacticalRevision:2,queueEvidenceScheme:2,actor:{id:"42",lifetime:"9007199254741105"},catalogueId,catalogueRevision:"9007199254741107",engineVersion:"2025.06.19",gameName:"BAR",gameVersion:"test-29926-0571aa8",contentSha256:"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",domain:"production"});
const nativeBasis=(sequence="20",frame=20)=>({token:Buffer.from("basis-token").toString("base64"),stateSequence:sequence,frame,matchIncarnation:matchId,processIncarnation:"process-1",stateChannelIncarnation:"channel-1",snapshotSendMonotonicNs:"9007199254742000",effectiveCadenceFrames:2});
const dispatch=()=>({brokerSessionId:Buffer.from(Array(16).fill(9)).toString("base64"),commandChannelIncarnation:"command-channel-1",batchSequence:"91",correlationId:"92",commandIndex:7,authorityEpoch:"3",moduleSha256:"a".repeat(64),moduleGeneration:"4",expectedQueueRevision:"18145486220354098388",matched:true});
const record=(phase="sample",basis=nativeBasis())=>({schema:"highbar.barc-stock-queue-trace/v1",runId:"stock-run",sequence:"1",phase,readFrame:21,perspectiveTeamId:0,nativeBasis:basis,context:context(),reader:{kind:"CallRules",status:"complete",request,response},queue:{revision:"18145486220354098388",entries:[{id:-710,codedOptions:32,tag:41,float32params:["3f800000","80000000"]}]},dispatch:phase==="sample"?null:dispatch()});
const browserBasis=basis=>canonicalObject(v1.ObservationBasis,encodeObject(v1.ObservationBasis,{token:basis.token,stateSequence:basis.stateSequence,nativeFrame:basis.frame,matchId:basis.matchIncarnation,processIncarnation:basis.processIncarnation,stateChannelIncarnation:basis.stateChannelIncarnation}));
const observations=basis=>({host:{nativeBasis:basis,actor:{id:"42",lifetime:"9007199254741105"},catalogue:{id:catalogueId,revision:"9007199254741107",contentSha256:context().contentSha256}},browser:{basis:browserBasis(basis),tactical:{actors:[{actor:{id:"42",lifetime:"9007199254741105"},queue:[{domain:"QUEUE_DOMAIN_FACTORY_PRODUCTION",revision:"18145486220354098388",complete:true,evidenceScheme:"NATIVE_QUEUE_EVIDENCE_SCHEME_STOCK_LUA_SUPPORTED_FIELDS_V1"}]}]}}});
const codec={canonicalObject,encodeObject,v1};

test("scheme2 revision vector and actual production codec normalization preserve signed zero",()=>{
  const value=record();assert.equal(computeStockRevision(value.context,[{domain:"production",...value.queue.entries[0]}]),"18145486220354098388");const actual=observations(value.nativeBasis),normalized=normalizeStockSample(value,actual.host,actual.browser,codec);assert.equal(normalized.value.entries[0].float32params[1],"80000000");assert.deepEqual(normalized.value.basis,actual.browser.basis);assert.equal(normalized.value.catalogueId,catalogueId);
});

test("stock trace parsing is closed, contiguous and complete",()=>{
  const value=record();assert.equal(parseStockTraceJsonl(`${JSON.stringify(value)}\n`)[0].queue.revision,value.queue.revision);assert.throws(()=>parseClosedJson('{"a":1,"a":2}'),/duplicate JSON key/);assert.throws(()=>parseStockTraceJsonl(JSON.stringify(value)),/complete line/);const cross={...value,runId:"other",sequence:"2"};assert.throws(()=>parseStockTraceJsonl(`${JSON.stringify(value)}\n${JSON.stringify(cross)}\n`),/run\/sequence/);const unknown={...value,extra:true};assert.throws(()=>validateStockTraceRecord(unknown),/keys changed/);
});

test("trace bounds and sample/final identities fail closed",()=>{
  assert.throws(()=>parseStockTraceJsonl(`${"x".repeat(32769)}\n`),/line\/record bound/);const tooManyParams=record();tooManyParams.queue.entries[0].float32params=Array(17).fill("3f800000");assert.throws(()=>validateStockTraceRecord(tooManyParams),/stock queue entry changed/);const numericBits=record();numericBits.queue.entries[0].float32params=[12345678];assert.throws(()=>validateStockTraceRecord(numericBits),/stock queue entry changed/);const sampleWithDispatch=record();sampleWithDispatch.dispatch=dispatch();assert.throws(()=>validateStockTraceRecord(sampleWithDispatch),/sample trace fabricated dispatch/);const finalWithoutDispatch=record("final-read");finalWithoutDispatch.dispatch=null;assert.throws(()=>validateStockTraceRecord(finalWithoutDispatch),/final read lacks dispatch/);
});

test("unavailable and malformed reads cannot become queue evidence",()=>{
  for(const status of ["unavailable","malformed"]){const value=record();value.reader={...value.reader,status,response:null};value.queue=null;validateStockTraceRecord(value);assert.throws(()=>normalizeStockSample(value,{}, {},codec),/complete sample/)}const invented=record();invented.reader.status="unavailable";assert.throws(()=>validateStockTraceRecord(invented),/fabricated queue evidence/);
});

test("normalization refuses wrong catalogue, basis, lifetime and browser revision",()=>{
  const value=record(),actual=observations(value.nativeBasis);for(const mutate of [host=>host.catalogue.contentSha256="b".repeat(64),host=>host.actor.lifetime="9",host=>host.nativeBasis={...host.nativeBasis,stateSequence:"21"}]){const wrong=structuredClone(actual.host);mutate(wrong);assert.throws(()=>normalizeStockSample(value,wrong,actual.browser,codec),/changed|differ/)}const wrongBrowser=structuredClone(actual.browser);wrongBrowser.basis.stateSequence="21";assert.throws(()=>normalizeStockSample(value,actual.host,wrongBrowser,codec),/basis bytes/);const wrongRevision=structuredClone(actual.browser);wrongRevision.tactical.actors[0].queue[0].revision="1";assert.throws(()=>normalizeStockSample(value,actual.host,wrongRevision,codec),/exact stock queue/);
});

test("final-read joins native binding to actual host/browser result without equating command index and child index",()=>{
  const sampleRecord=record(),actual=observations(sampleRecord.nativeBasis),sample=normalizeStockSample(sampleRecord,actual.host,actual.browser,codec),final=record("final-read");final.sequence="2";const parentId=Buffer.alloc(16,1).toString("base64"),inputId=Buffer.alloc(16,2).toString("base64"),module={sha256:Buffer.from("a".repeat(64),"hex").toString("base64"),generation:"4"},controller={sessionId:dispatch().brokerSessionId,controllerId:Buffer.alloc(16,3).toString("base64"),controllerIncarnation:"controller-1",authorityEpoch:"3"},submit={parentId,inputId,module,controller,basis:sample.value.basis,intent:{actors:[sample.value.actor],actorTacticalBindings:[{actor:sample.value.actor,queueRevisions:[{domain:sample.value.domain,revision:sample.value.queueRevision}]}]}};const value=(stage,status)=>canonicalObject(v1.LiveResult,encodeObject(v1.LiveResult,{resultSequence:String({LIVE_RESULT_STAGE_BROKER_ADMISSION:1,LIVE_RESULT_STAGE_NATIVE_ADMISSION:2,LIVE_RESULT_STAGE_NATIVE_DISPATCH:3,LIVE_RESULT_STAGE_UNKNOWN:4}[stage]),parentId,inputId,module,controller,basis:sample.value.basis,batchSequence:"91",correlationId:"92",childIndex:0,childCount:1,actor:sample.value.actor,stage,status,disposition:"LIVE_RESULT_DISPOSITION_RECORDED",commandChannelIncarnation:"command-channel-1"})),browser=[value("LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"),value("LIVE_RESULT_STAGE_NATIVE_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"),value("LIVE_RESULT_STAGE_NATIVE_DISPATCH","LIVE_RESULT_STATUS_APPLIED")],guid="01010101-0101-0101-0101-010101010101",inputGuid="02020202-0202-0202-0202-020202020202",wrap=row=>({parentId:guid,inputId:inputGuid,batchSequence:"91",correlationId:"92",commandChannelIncarnation:"command-channel-1",moduleGeneration:"4",moduleSha256:"a".repeat(64),authorityEpoch:"3",wireEnvelope:JSON.stringify({result:row})}),host=browser.map(wrap);const joined=joinStockFinalRead(final,sample,host,submit,browser,codec);assert.equal(joined.value.nativeCommandIndex,7);assert.equal(joined.value.childIndex,0);const foreign=structuredClone(browser);foreign[2].correlationId="99";assert.throws(()=>joinStockFinalRead(final,sample,host,submit,foreign,codec),/browser lifecycle|host\/browser/);assert.throws(()=>joinStockFinalRead(final,sample,host,submit,[...browser,browser[2]],codec),/duplicate|terminal/);const unknown=[browser[0],value("LIVE_RESULT_STAGE_UNKNOWN","LIVE_RESULT_STATUS_EXPIRED")],unknownJoin=joinStockFinalRead(final,sample,unknown.map(wrap),submit,unknown,codec);assert.equal(unknownJoin.value.status,"LIVE_RESULT_STATUS_EXPIRED");const zeroBasis=structuredClone(sample);delete zeroBasis.value.basis.nativeFrame;final.nativeBasis.frame=0;assert.doesNotThrow(()=>joinStockFinalRead(final,zeroBasis,host.map(row=>({...row,wireEnvelope:row.wireEnvelope.replace('"nativeFrame":20,','')})),{...submit,basis:zeroBasis.value.basis},browser.map(row=>({...row,basis:zeroBasis.value.basis})),codec));
});

test("same stock revision at fresh bases is valid while exact same-basis duplication refuses",()=>{
  const first=record(),actual=observations(first.nativeBasis),one=normalizeStockSample(first,actual.host,actual.browser,codec),freshBasis=nativeBasis("21",21),secondRecord=record("sample",freshBasis),fresh=observations(freshBasis),two=normalizeStockSample(secondRecord,fresh.host,fresh.browser,codec),expected={profile:"barc-live-tactical-stock-v1",tacticalRevision:2,queueEvidenceScheme:2,queueBridge:"barc-stock-queue-reader-v1",supportedQueueFields:["domain","id","options.coded","tag","float32params"],actor:one.value.actor,catalogue:{id:catalogueId,revision:context().catalogueRevision,contentSha256:context().contentSha256},source:{matchId:matchId,processIncarnation:"process-1",stateChannelIncarnation:"channel-1"}},factory=policy=>({count:1,queuePolicy:policy,catalogueId,catalogueRevision:context().catalogueRevision}),binding={actor:one.value.actor,queueRevisions:[{domain:one.value.domain,revision:one.value.queueRevision}]},append={parentId:"append",basis:one.value.basis,intent:{action:"factoryProduce",actors:[one.value.actor],actorTacticalBindings:[binding],factoryProduce:factory("TACTICAL_QUEUE_POLICY_APPEND")}},replace={parentId:"replace",basis:one.value.basis,intent:{action:"factoryProduce",actors:[one.value.actor],actorTacticalBindings:[structuredClone(binding)],factoryProduce:factory("TACTICAL_QUEUE_POLICY_REPLACE")}},result=(parentId,stage,status)=>({kind:"result",value:{parentId,childIndex:0,childCount:1,actor:one.value.actor,basis:one.value.basis,stage,status}}),rows=[one,two,{kind:"submit",value:append},{kind:"submit",value:replace},result("append","LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"),result("append","LIVE_RESULT_STAGE_NATIVE_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"),result("append","LIVE_RESULT_STAGE_NATIVE_DISPATCH","LIVE_RESULT_STATUS_APPLIED"),result("replace","LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_REJECTED")];assert.notDeepEqual(one.value.basis,two.value.basis);assert.equal(assertStockQueueEvidence(rows,expected).appliedChildCount,1);assert.throws(()=>assertStockQueueEvidence([one,structuredClone(one),...rows.slice(2)],expected),/duplicated an actor\/domain\/revision\/basis/);
});

const artifacts=()=>Object.fromEntries(["engine","plugin","stockOverlay","baseGame","map","passiveFixture","nativeHost","receiverArchive","client","guest","codecManifest","helperManifest"].map(role=>[role,{path:`artifacts/${role}`,sha256:"a".repeat(64)}]));
const handoffInputs=()=>{const staticPacket={runId:"stock-run",packetSha256:"b".repeat(64),selection:{product:"local",mode:"pointer",caseId:"stock-smoke-count1",count:1},source:{fsbarCommit:"b787c37d20484eb66649fd9b1f98e28730492433",highbarCommit:"c".repeat(40)},artifacts:artifacts(),paths:{codecDirectory:"/attempt/codec",receiverRoot:"/attempt/receiver",hostTrace:"/attempt/host.jsonl",stockTrace:"/attempt/stock.jsonl",capture:"/attempt/capture.jsonl",output:"/attempt/out.json"},receiverUrl:"http://127.0.0.1:3800/barc/?barc-profile=barc-live-tactical-stock-v1"},ready={schema:"fsbar.barc-native-live-host/v2",sourceCommit:staticPacket.source.fsbarCommit,profile:"barc-live-tactical-stock-v1",protocolVersion:2,tacticalRevision:2,queueEvidenceScheme:2,guestAbiVersion:1,grpcAddress:"127.0.0.1:5021",gatewayUrl:"ws://127.0.0.1:3900/barc-live",allowedOrigin:"http://127.0.0.1:3800",sessionId:"33221100-5544-7766-8899-aabbccddeeff",credential:"d".repeat(64),nativeTracePath:staticPacket.paths.hostTrace,fixtureMode:false},metadata={profile:ready.profile,tacticalRevision:2,queueEvidenceScheme:2,queueBridge:"barc-stock-queue-reader-v1",actor:{id:"42",lifetime:"9007199254741105"},catalogue:{id:catalogueId,revision:context().catalogueRevision,contentSha256:context().contentSha256},source:{matchId,processIncarnation:"process-1",stateChannelIncarnation:"channel-1"}},setup={factory:{...metadata.actor},builder:{id:"43",lifetime:"2"},combatTarget:{id:"44",lifetime:"3"},existingProductionDefinitionId:710,productDefinitionId:711,positions:{rally:{x:100,z:200},move:{x:300,z:400}}};return{staticPacket,ready,metadata,setup}};
test("selected Count1 smoke handoff materializes only from actual stock ready/metadata/setup",()=>{const inputs=handoffInputs(),value=materializeStockHandoff(inputs.staticPacket,inputs.ready,inputs.metadata,inputs.setup);assert.equal(validateStockSmokeHandoff(value),value);assert.equal(value.selection.count,1);assert.equal(value.expected.actor.id,"42");const legacy=structuredClone(inputs.ready);legacy.tacticalRevision=1;assert.throws(()=>materializeStockHandoff(inputs.staticPacket,legacy,inputs.metadata,inputs.setup),/readiness changed/);const placeholder=structuredClone(inputs.ready);placeholder.credential="placeholder";assert.throws(()=>materializeStockHandoff(inputs.staticPacket,placeholder,inputs.metadata,inputs.setup),/connection identity/)});

test("frozen-prefix CLI joins four actual full lifecycles and is the sole output writer",()=>{
  const sampleRecord=record(),final=record("final-read");final.sequence="2";const actual=observations(sampleRecord.nativeBasis),sample=normalizeStockSample(sampleRecord,actual.host,actual.browser,codec),source={fsbarCommit:"b787c37d20484eb66649fd9b1f98e28730492433",highbarCommit:"c".repeat(40)},hostWriter={pid:101,startTicks:"11",uid:1000},browserWriter={pid:102,startTicks:"12",uid:1000,executable:"/usr/bin/node",sourcePath:"/source/tactical-native-journey.spec.js",sourceSha256:"d".repeat(64)},hostEvents=[],browserEvents=[{kind:"observation",value:actual.browser}],module={sha256:Buffer.from("a".repeat(64),"hex").toString("base64"),generation:"4"},controller={sessionId:dispatch().brokerSessionId,controllerId:Buffer.alloc(16,3).toString("base64"),controllerIncarnation:"controller-1",authorityEpoch:"3"},dotnetGuid=value=>{const b=Buffer.from(value,"base64"),h=i=>b[i].toString(16).padStart(2,"0");return[h(3)+h(2)+h(1)+h(0),h(5)+h(4),h(7)+h(6),h(8)+h(9),[10,11,12,13,14,15].map(h).join("")].join("-")};
  const actionValues=[{action:"setRally",setRally:{position:{x:1,z:2}}},{action:"factoryProduce",factoryProduce:{definitionId:711,count:1,queuePolicy:"TACTICAL_QUEUE_POLICY_APPEND"}},{action:"move",move:{position:{x:3,z:4},policy:"MOVE_POLICY_REPLACE"}},{action:"attack",attack:{target:sample.value.actor}}];for(let operation=0;operation<4;operation++){const parentId=Buffer.alloc(16,operation+1).toString("base64"),inputId=Buffer.alloc(16,operation+11).toString("base64"),submit={parentId,inputId,module,controller,basis:sample.value.basis,intent:{actors:[sample.value.actor],actorTacticalBindings:[{actor:sample.value.actor,queueRevisions:[{domain:sample.value.domain,revision:sample.value.queueRevision}]}],...actionValues[operation]}};browserEvents.push({kind:"submit",value:submit});for(const [offset,stage,status] of [[1,"LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"],[2,"LIVE_RESULT_STAGE_NATIVE_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"],[3,"LIVE_RESULT_STAGE_NATIVE_DISPATCH","LIVE_RESULT_STATUS_APPLIED"]]){const correlation=String(92+operation),result=canonicalObject(v1.LiveResult,encodeObject(v1.LiveResult,{resultSequence:String(operation*3+offset),parentId,inputId,module,controller,basis:sample.value.basis,batchSequence:"91",correlationId:correlation,childIndex:0,childCount:1,actor:sample.value.actor,stage,status,disposition:"LIVE_RESULT_DISPOSITION_RECORDED",commandChannelIncarnation:"command-channel-1"}));browserEvents.push({kind:"result",value:result});hostEvents.push({kind:"result",value:{parentId:dotnetGuid(parentId),inputId:dotnetGuid(inputId),batchSequence:"91",correlationId:correlation,commandChannelIncarnation:"command-channel-1",moduleGeneration:"4",moduleSha256:"a".repeat(64),authorityEpoch:"3",wireEnvelope:JSON.stringify({result})}})}}browserEvents.push({kind:"ui-refusal",value:{action:"factoryProduce",queuePolicy:"TACTICAL_QUEUE_POLICY_REPLACE",submitCountBefore:4,submitCountAfter:4,detail:"No Append fallback"}});
  final.dispatch.correlationId="93";const hostMetadata={kind:"live-metadata",value:{tactical:{basis:sampleRecord.nativeBasis,actors:[{actor:sampleRecord.context.actor}],catalogueId},catalogue:[{catalogueId,catalogueRevision:sampleRecord.context.catalogueRevision,content:{gameContentSha256:Buffer.from(sampleRecord.context.contentSha256,"hex").toString("base64")}}]}};hostEvents.unshift(hostMetadata);const journal=(schema,writer,events)=>[{kind:"header",value:{selectedCase:"stock-smoke-count1"}},...events,{kind:"complete",value:{selectedCase:"stock-smoke-count1"}}].map((row,index)=>JSON.stringify({schema,runId:"stock-run",sequence:String(index+1),kind:row.kind,writer,source,value:row.value})).join("\n")+"\n",stockText=`${JSON.stringify(sampleRecord)}\n${JSON.stringify(final)}\n`,hostText=journal("fsbar.barc-stock-host-journal/v1",hostWriter,hostEvents),browserText=journal("fsbar.barc-stock-browser-capture/v1",browserWriter,browserEvents),normalized=normalizeFrozenStockEvidence(stockText,hostText,browserText);assert.equal(normalized.finalReadJoins.length,1);assert.equal(normalized.finalReadJoins[0].value.parentId,browserEvents.find(row=>row.kind==="submit"&&row.value.intent.action==="factoryProduce").value.parentId);assert.equal(normalized.claims.nativeAcceptance,"0/6");
  const runCli=(stock,hostJournal,browserJournal,accepted)=>{const dir=mkdtempSync(join(tmpdir(),"stock-normalizer-")),paths=["stock.jsonl","host.jsonl","browser.jsonl","output.json"].map(name=>join(dir,name));try{writeFileSync(paths[0],stock);writeFileSync(paths[1],hostJournal);writeFileSync(paths[2],browserJournal);const argv=[new URL("./stock-native-trace.mjs",import.meta.url).pathname,"--stock-trace",paths[0],"--host-snapshot",paths[1],"--browser-observation",paths[2],"--output",paths[3]],result=spawnSync(process.execPath,argv,{encoding:"utf8"});if(accepted){assert.equal(result.status,0,result.stderr);assert.equal(parseClosedJson(readFileSync(paths[3],"utf8")).schema,"fsbar.barc-stock-native-smoke-evidence/v1");const second=spawnSync(process.execPath,argv,{encoding:"utf8"});assert.equal(second.status,2);assert.match(second.stderr,/refused/)}else{assert.equal(result.status,2);assert.match(result.stderr,/refused/);assert.equal(existsSync(paths[3]),false)}}finally{rmSync(dir,{recursive:true,force:true})}};
  runCli(stockText,hostText,browserText,true);
  const append=browserEvents.find(row=>row.kind==="submit"&&row.value.intent.action==="factoryProduce").value,appendGuid=dotnetGuid(append.parentId),hostResult=row=>row.kind==="result"&&row.value.parentId===appendGuid,browserResult=row=>row.kind==="result"&&row.value.parentId===append.parentId,hostStage=row=>parseClosedJson(row.value.wireEnvelope).result.stage;
  const missingHost=hostEvents.filter(row=>!hostResult(row)||hostStage(row)==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"),missingBrowser=browserEvents.filter(row=>!browserResult(row)||row.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH");runCli(stockText,journal("fsbar.barc-stock-host-journal/v1",hostWriter,missingHost),journal("fsbar.barc-stock-browser-capture/v1",browserWriter,missingBrowser),false);
  const duplicateBrowser=structuredClone(browserEvents),duplicateAt=duplicateBrowser.findIndex(row=>browserResult(row)&&row.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION");duplicateBrowser.splice(duplicateAt+1,0,structuredClone(duplicateBrowser[duplicateAt]));runCli(stockText,hostText,journal("fsbar.barc-stock-browser-capture/v1",browserWriter,duplicateBrowser),false);
  const contradictoryBrowser=structuredClone(browserEvents),nativeAt=contradictoryBrowser.findIndex(row=>browserResult(row)&&row.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"),contradictory=structuredClone(contradictoryBrowser[nativeAt]);contradictory.value.status="LIVE_RESULT_STATUS_REJECTED";contradictoryBrowser.splice(nativeAt+1,0,contradictory);runCli(stockText,hostText,journal("fsbar.barc-stock-browser-capture/v1",browserWriter,contradictoryBrowser),false);
  const reorderedBrowser=structuredClone(browserEvents),brokerAt=reorderedBrowser.findIndex(row=>browserResult(row)&&row.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"),admissionAt=reorderedBrowser.findIndex(row=>browserResult(row)&&row.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION");[reorderedBrowser[brokerAt],reorderedBrowser[admissionAt]]=[reorderedBrowser[admissionAt],reorderedBrowser[brokerAt]];runCli(stockText,hostText,journal("fsbar.barc-stock-browser-capture/v1",browserWriter,reorderedBrowser),false);
  const foreignBrowser=structuredClone(browserEvents),foreignAt=foreignBrowser.findIndex(row=>browserResult(row)&&row.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION");foreignBrowser[foreignAt].value.parentId=Buffer.alloc(16,9).toString("base64");runCli(stockText,hostText,journal("fsbar.barc-stock-browser-capture/v1",browserWriter,foreignBrowser),false);
  const correlationHost=structuredClone(hostEvents),correlationBrowser=structuredClone(browserEvents),move=browserEvents.find(row=>row.kind==="submit"&&row.value.intent.action==="move").value,moveGuid=dotnetGuid(move.parentId),changedHost=correlationHost.find(row=>row.kind==="result"&&row.value.parentId===moveGuid&&parseClosedJson(row.value.wireEnvelope).result.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"),changedBrowser=correlationBrowser.find(row=>row.kind==="result"&&row.value.parentId===move.parentId&&row.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"),changedWire=parseClosedJson(changedHost.value.wireEnvelope);changedHost.value.correlationId="999";changedWire.result.correlationId="999";changedHost.value.wireEnvelope=JSON.stringify(changedWire);changedBrowser.value.correlationId="999";runCli(stockText,journal("fsbar.barc-stock-host-journal/v1",hostWriter,correlationHost),journal("fsbar.barc-stock-browser-capture/v1",browserWriter,correlationBrowser),false);
  const rallyFinal=structuredClone(final);rallyFinal.dispatch.correlationId="92";runCli(`${JSON.stringify(sampleRecord)}\n${JSON.stringify(rallyFinal)}\n`,hostText,browserText,false);
});
