import test from "node:test";
import assert from "node:assert/strict";
import { canonicalObject, encodeObject, v1 } from "../../src/Broker.Browser.Contracts/generated/codec.js";
import { assertStockQueueEvidence } from "./tactical-native-evidence.mjs";
import { computeStockRevision, joinStockFinalRead, materializeStockHandoff, normalizeStockSample, parseClosedJson, parseStockTraceJsonl, validateStockSmokeHandoff, validateStockTraceRecord } from "./stock-native-trace.mjs";

const request="BARC_QUEUE_REQUEST/1\nlength=00000101\nbridge=barc-stock-queue-reader-v1\ndomain=production\nunit=42\nend\n";
const response="BARC_QUEUE_RESPONSE/1\nlength=00000244\nbridge=barc-stock-queue-reader-v1\nrequest-sha256=b01b44c1eaea587730eae794c0b87e4e05dddecfb508abd295ac1e138a0f5960\nstatus=ok\ndomain=production\nunit=42\ncount=1\nrow=production|-710|32|41|3f800000,80000000\nend\n";
const catalogueId=Buffer.from(Array.from({length:16},(_,index)=>index)).toString("base64"),matchId=Buffer.from(Array.from({length:16},(_,index)=>index+16)).toString("base64");
const context=()=>({profile:"barc-live-tactical-stock-v1",tacticalRevision:2,queueEvidenceScheme:2,actor:{id:"42",lifetime:"9007199254741105"},catalogueId,catalogueRevision:"9007199254741107",engineVersion:"2025.06.19",gameName:"BAR",gameVersion:"test-29926-0571aa8",contentSha256:"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",domain:"production"});
const nativeBasis=(sequence="20",frame=20)=>({token:Buffer.from("basis-token").toString("base64"),stateSequence:sequence,frame,matchIncarnation:matchId,processIncarnation:"process-1",stateChannelIncarnation:"channel-1",snapshotSendMonotonicNs:"9007199254742000",effectiveCadenceFrames:2});
const dispatch=()=>({brokerSessionId:Buffer.from(Array(16).fill(9)).toString("base64"),commandChannelIncarnation:"command-channel-1",batchSequence:"91",correlationId:"92",commandIndex:7,authorityEpoch:"3",moduleSha256:"a".repeat(64),moduleGeneration:"4",expectedQueueRevision:"18145486220354098388",matched:true});
const record=(phase="sample",basis=nativeBasis())=>({schema:"highbar.barc-stock-queue-trace/v1",runId:"stock-run",sequence:"1",phase,readFrame:21,perspectiveTeamId:0,nativeBasis:basis,context:context(),reader:{kind:"CallRules",status:"complete",request,response},queue:{revision:"18145486220354098388",entries:[{id:-710,codedOptions:32,tag:41,float32params:["3f800000","80000000"]}]},dispatch:phase==="sample"?null:dispatch()});
const browserBasis=basis=>canonicalObject(v1.ObservationBasis,encodeObject(v1.ObservationBasis,{token:basis.token,stateSequence:basis.stateSequence,nativeFrame:basis.frame,matchId:basis.matchIncarnation,processIncarnation:basis.processIncarnation,stateChannelIncarnation:basis.stateChannelIncarnation}));
const observations=basis=>({host:{nativeBasis:basis,actor:{id:"42",lifetime:"9007199254741105"},catalogue:{id:catalogueId,revision:"9007199254741107",contentSha256:context().contentSha256}},browser:{basis:browserBasis(basis),tactical:{actors:[{actor:{id:"42",lifetime:"9007199254741105"},queue:[{domain:"QUEUE_DOMAIN_FACTORY_PRODUCTION",revision:"18145486220354098388",complete:true,evidenceScheme:"NATIVE_QUEUE_EVIDENCE_SCHEME_STOCK_LUA_SUPPORTED_FIELDS_V1"}]}]}}});
const codec={canonicalObject,encodeObject,v1};

test("scheme2 revision vector and actual production codec normalization preserve signed zero",()=>{
  const value=record();assert.equal(computeStockRevision(value.context,[{domain:"production",...value.queue.entries[0]}]),"18145486220354098388");const actual=observations(value.nativeBasis),normalized=normalizeStockSample(value,actual.host,actual.browser,codec);assert.equal(normalized.value.entries[0].float32params[1],"80000000");assert.deepEqual(normalized.value.basis,actual.browser.basis);assert.equal(normalized.value.catalogueId,catalogueId);
});

test("stock trace parsing is closed, contiguous and complete",()=>{
  const value=record();assert.equal(parseStockTraceJsonl(`${JSON.stringify(value)}\n`)[0].queue.revision,value.queue.revision);assert.throws(()=>parseClosedJson('{"a":1,"a":2}'),/duplicate JSON key/);assert.throws(()=>parseStockTraceJsonl(JSON.stringify(value)),/complete line/);const cross={...value,runId:"other",sequence:"2"};assert.throws(()=>parseStockTraceJsonl(`${JSON.stringify(value)}\n${JSON.stringify(cross)}\n`),/run\/sequence/);const unknown={...value,extra:true};assert.throws(()=>validateStockTraceRecord(unknown),/keys changed/);
});

test("trace bounds and sample/final identities fail closed",()=>{
  assert.throws(()=>parseStockTraceJsonl(`${"x".repeat(32769)}\n`),/line\/record bound/);const tooManyParams=record();tooManyParams.queue.entries[0].float32params=Array(17).fill("3f800000");assert.throws(()=>validateStockTraceRecord(tooManyParams),/stock queue entry changed/);const numericBits=record();numericBits.queue.entries[0].float32params=[12345678];assert.throws(()=>validateStockTraceRecord(numericBits),/stock queue entry changed/);const sampleWithDispatch=record();sampleWithDispatch.dispatch=dispatch();assert.throws(()=>validateStockTraceRecord(sampleWithDispatch),/sample trace fabricated dispatch/);const finalWithoutDispatch=record("final-read");finalWithoutDispatch.dispatch=null;assert.throws(()=>validateStockTraceRecord(finalWithoutDispatch),/final read lacks dispatch/);
});

test("unavailable and malformed reads cannot become queue evidence",()=>{
  for(const status of ["unavailable","malformed"]){const value=record();value.reader={...value.reader,status,response:null};value.queue=null;validateStockTraceRecord(value);assert.throws(()=>normalizeStockSample(value,{}, {},codec),/complete sample/)}const invented=record();invented.reader.status="unavailable";assert.throws(()=>validateStockTraceRecord(invented),/fabricated queue evidence/);
});

test("normalization refuses wrong catalogue, basis, lifetime and browser revision",()=>{
  const value=record(),actual=observations(value.nativeBasis);for(const mutate of [host=>host.catalogue.contentSha256="b".repeat(64),host=>host.actor.lifetime="9",host=>host.nativeBasis={...host.nativeBasis,stateSequence:"21"}]){const wrong=structuredClone(actual.host);mutate(wrong);assert.throws(()=>normalizeStockSample(value,wrong,actual.browser,codec),/changed|differ/)}const wrongBrowser=structuredClone(actual.browser);wrongBrowser.basis.stateSequence="21";assert.throws(()=>normalizeStockSample(value,actual.host,wrongBrowser,codec),/basis bytes/);const wrongRevision=structuredClone(actual.browser);wrongRevision.tactical.actors[0].queue[0].revision="1";assert.throws(()=>normalizeStockSample(value,actual.host,wrongRevision,codec),/exact stock queue/);
});

test("final-read joins native binding to actual host/browser result without equating command index and child index",()=>{
  const sampleRecord=record(),actual=observations(sampleRecord.nativeBasis),sample=normalizeStockSample(sampleRecord,actual.host,actual.browser,codec),final=record("final-read");final.sequence="2";const submit={parentId:"parent-1",basis:sample.value.basis,intent:{actors:[sample.value.actor],actorTacticalBindings:[{actor:sample.value.actor,queueRevisions:[{domain:sample.value.domain,revision:sample.value.queueRevision}]}]}};const host={...dispatch(),parentId:submit.parentId,actor:sample.value.actor,basis:sample.value.basis},browser={parentId:submit.parentId,actor:sample.value.actor,basis:sample.value.basis,childIndex:0,childCount:1,stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",status:"LIVE_RESULT_STATUS_APPLIED"};const joined=joinStockFinalRead(final,sample,host,submit,browser);assert.equal(joined.value.nativeCommandIndex,7);assert.equal(joined.value.childIndex,0);const missing={...host,correlationId:"99"};assert.throws(()=>joinStockFinalRead(final,sample,missing,submit,browser),/actual host result/);const unknown={...browser,parentId:"other"};assert.throws(()=>joinStockFinalRead(final,sample,host,submit,unknown),/actual browser result/);
});

test("same stock revision at fresh bases is valid while exact same-basis duplication refuses",()=>{
  const first=record(),actual=observations(first.nativeBasis),one=normalizeStockSample(first,actual.host,actual.browser,codec),freshBasis=nativeBasis("21",21),secondRecord=record("sample",freshBasis),fresh=observations(freshBasis),two=normalizeStockSample(secondRecord,fresh.host,fresh.browser,codec),expected={profile:"barc-live-tactical-stock-v1",tacticalRevision:2,queueEvidenceScheme:2,queueBridge:"barc-stock-queue-reader-v1",supportedQueueFields:["domain","id","options.coded","tag","float32params"],actor:one.value.actor,catalogue:{id:catalogueId,revision:context().catalogueRevision,contentSha256:context().contentSha256},source:{matchId:matchId,processIncarnation:"process-1",stateChannelIncarnation:"channel-1"}},factory=policy=>({count:1,queuePolicy:policy,catalogueId,catalogueRevision:context().catalogueRevision}),binding={actor:one.value.actor,queueRevisions:[{domain:one.value.domain,revision:one.value.queueRevision}]},append={parentId:"append",basis:one.value.basis,intent:{action:"factoryProduce",actors:[one.value.actor],actorTacticalBindings:[binding],factoryProduce:factory("TACTICAL_QUEUE_POLICY_APPEND")}},replace={parentId:"replace",basis:one.value.basis,intent:{action:"factoryProduce",actors:[one.value.actor],actorTacticalBindings:[structuredClone(binding)],factoryProduce:factory("TACTICAL_QUEUE_POLICY_REPLACE")}},result=(parentId,stage,status)=>({kind:"result",value:{parentId,childIndex:0,childCount:1,actor:one.value.actor,basis:one.value.basis,stage,status}}),rows=[one,two,{kind:"submit",value:append},{kind:"submit",value:replace},result("append","LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"),result("append","LIVE_RESULT_STAGE_NATIVE_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"),result("append","LIVE_RESULT_STAGE_NATIVE_DISPATCH","LIVE_RESULT_STATUS_APPLIED"),result("replace","LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_REJECTED")];assert.notDeepEqual(one.value.basis,two.value.basis);assert.equal(assertStockQueueEvidence(rows,expected).appliedChildCount,1);assert.throws(()=>assertStockQueueEvidence([one,structuredClone(one),...rows.slice(2)],expected),/duplicated an actor\/domain\/revision\/basis/);
});

const artifacts=()=>Object.fromEntries(["engine","plugin","stockOverlay","baseGame","map","passiveFixture","nativeHost","receiverArchive","client","guest","codecManifest","helperManifest"].map(role=>[role,{path:`artifacts/${role}`,sha256:"a".repeat(64)}]));
const handoffInputs=()=>{const staticPacket={runId:"stock-run",packetSha256:"b".repeat(64),selection:{product:"local",mode:"pointer",caseId:"stock-smoke-count1",count:1},source:{fsbarCommit:"b787c37d20484eb66649fd9b1f98e28730492433",highbarCommit:"c".repeat(40)},artifacts:artifacts(),paths:{codecDirectory:"/attempt/codec",receiverRoot:"/attempt/receiver",hostTrace:"/attempt/host.jsonl",stockTrace:"/attempt/stock.jsonl",capture:"/attempt/capture.jsonl",output:"/attempt/out.json"},receiverUrl:"http://127.0.0.1:3800/barc/?barc-profile=barc-live-tactical-stock-v1"},ready={schema:"fsbar.barc-native-live-host/v2",sourceCommit:staticPacket.source.fsbarCommit,profile:"barc-live-tactical-stock-v1",protocolVersion:2,tacticalRevision:2,queueEvidenceScheme:2,guestAbiVersion:1,grpcAddress:"127.0.0.1:5021",gatewayUrl:"ws://127.0.0.1:3900/barc-live",allowedOrigin:"http://127.0.0.1:3800",sessionId:"33221100-5544-7766-8899-aabbccddeeff",credential:"d".repeat(64),nativeTracePath:staticPacket.paths.hostTrace,fixtureMode:false},metadata={profile:ready.profile,tacticalRevision:2,queueEvidenceScheme:2,queueBridge:"barc-stock-queue-reader-v1",actor:{id:"42",lifetime:"9007199254741105"},catalogue:{id:catalogueId,revision:context().catalogueRevision,contentSha256:context().contentSha256},source:{matchId,processIncarnation:"process-1",stateChannelIncarnation:"channel-1"}},setup={factory:{...metadata.actor},builder:{id:"43",lifetime:"2"},combatTarget:{id:"44",lifetime:"3"},existingProductionDefinitionId:710,productDefinitionId:711,positions:{rally:{x:100,z:200},move:{x:300,z:400}}};return{staticPacket,ready,metadata,setup}};
test("selected Count1 smoke handoff materializes only from actual stock ready/metadata/setup",()=>{const inputs=handoffInputs(),value=materializeStockHandoff(inputs.staticPacket,inputs.ready,inputs.metadata,inputs.setup);assert.equal(validateStockSmokeHandoff(value),value);assert.equal(value.selection.count,1);assert.equal(value.expected.actor.id,"42");const legacy=structuredClone(inputs.ready);legacy.tacticalRevision=1;assert.throws(()=>materializeStockHandoff(inputs.staticPacket,legacy,inputs.metadata,inputs.setup),/readiness changed/);const placeholder=structuredClone(inputs.ready);placeholder.credential="placeholder";assert.throws(()=>materializeStockHandoff(inputs.staticPacket,placeholder,inputs.metadata,inputs.setup),/connection identity/)});
