import test from "node:test";
import assert from "node:assert/strict";
import { assertCanonicalLifecycle, causalActionWindow, exactHealthDecreased, exactObservedUnit, isExactStaleBasisRefusal, isFreshPhysicalReplacement, newlyCompletedUnits, plannedChildCount, requiredManualFamilies, sanitizedLifecycle, validateTacticalHandoff, waitForTerminalOrClose } from "./tactical-native-evidence.mjs";

const ref=(id,lifetime="9007199254740993")=>({id:String(id),lifetime}),pos={build:{x:100,z:200},rally:{x:300,z:400},reclaim:{x:500,z:600}};
const journey=(product,mode)=>({id:`${product}-${mode}`,mode,receiverUrl:`http://127.0.0.1:3800/barc/?barc-profile=barc-live-tactical-v1`,allowedOrigin:"http://127.0.0.1:3800",gatewayUrl:"ws://127.0.0.1:3900/barc-live",expectedSessionId:"33221100-5544-7766-8899-aabbccddeeff",credential:`secret-${product}-${mode}`,nativeTracePath:"/private/native.jsonl",engineTracePath:"/private/engine.log",outputPath:`/private/${product}-${mode}.jsonl`,builder:ref(0),repairTarget:ref(1),reclaimUnitTarget:ref(4),factory:ref(2),combatTarget:ref(3),feature:ref(0,"9007199254740995"),areaFeature:ref(5,"9007199254740997"),mixedActors:[ref(0),ref(6)],mixedAppliedActor:ref(0),mixedRefusedActor:ref(6),mixedAction:"guard",modeActors:{constructionPriority:ref(0),cloakDesire:ref(6)},buildDefinitionId:710,productDefinitionId:711,positions:pos,steps:(mode==="importedGuest"?["importedPolicyEffect","zeroWriteRefusal"]:requiredManualFamilies).map(family=>({family})),...(mode==="keyboard"?{keyboardTargets:"t/f/l-v1"}:{}),...(mode==="importedGuest"?{guestPath:"/private/custom.wasm",guestSha256:"a".repeat(64),importedExpectedAction:"build",importedActors:[ref(0)]}:{})});
const handoff=()=>({schema:"fsbar.barc-tactical-native-browser-handoff/v1",fixtureMode:false,sourceCommit:"b".repeat(40),archiveSha256:"c".repeat(64),clientSha256:"d".repeat(64),pluginSha256:"e".repeat(64),engineSha256:"f".repeat(64),profile:"barc-live-tactical-v1",protocolVersion:2,tacticalRevision:1,guestAbiVersion:1,codecDirectory:"/receiver/generated",products:["local","generated"].map(id=>({id,receiverRoot:`/${id}`,journeys:["pointer","keyboard","importedGuest"].map(mode=>journey(id,mode))}))});

test("six-journey handoff pins exact roles, keyboard controls and imported bytes",()=>{const value=handoff();assert.equal(validateTacticalHandoff(value),value);const bad=structuredClone(value);bad.products[0].journeys[1].keyboardTargets="pointer-assisted";assert.throws(()=>validateTacticalHandoff(bad),/keyboard target-control/)});
test("every child needs a terminal outcome and mixed means native child divergence",()=>{const rows=[];for(let childIndex=0;childIndex<2;childIndex++)for(const[stage,status]of[["BrokerAdmission","Accepted"],["NativeAdmission",childIndex?"Rejected":"Accepted"],["NativeDispatch",childIndex?"Skipped":"Applied"]])rows.push({kind:"result",parentId:"p",childIndex,childCount:2,stage,status});assert.equal(assertCanonicalLifecycle(rows,[{id:"p",childCount:2,requireMixed:true}]),true);assert.throws(()=>assertCanonicalLifecycle(rows.filter(x=>x.stage!=="NativeDispatch"),[{id:"p",childCount:2}]),/terminal outcome/)});
test("factory fanout uses actor count times requested count and missing children fail",()=>{assert.equal(plannedChildCount({actors:[ref(0),ref(1)],factoryProduce:{count:3}}),6);assert.throws(()=>assertCanonicalLifecycle([{kind:"result",parentId:"p",childIndex:0,childCount:2,stage:"BrokerAdmission",status:"Rejected"}],[{id:"p",childCount:2}]),/child 1/)});
test("terminal wait distinguishes feedback, refusal, forwarded timeout and pre-terminal close",async()=>{for(const value of [{parentId:"p",childIndex:0,stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",status:"LIVE_RESULT_STATUS_APPLIED"},{parentId:"p",childIndex:0,stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",status:"LIVE_RESULT_STATUS_REJECTED"},{parentId:"p",childIndex:0,stage:"LIVE_RESULT_STAGE_UNKNOWN",status:"LIVE_RESULT_STATUS_EXPIRED"}])assert.equal(await waitForTerminalOrClose([{kind:"result",value}],{closed:false,error:false},"p",1,{timeoutMs:10}),1);await assert.rejects(waitForTerminalOrClose([],{closed:true,error:false},"p",1,{timeoutMs:1000}),/closed before terminal/);await assert.rejects(waitForTerminalOrClose([],{closed:false,error:false},"p",1,{timeoutMs:5,intervalMs:1}),/timed out/)});
test("partial lifecycle is fixed counts only",()=>{const privateValue="credential-uuid-coordinate";const summary=sanitizedLifecycle([{kind:"submit",value:{parentId:privateValue}},{kind:"result",value:{stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",detail:privateValue}}],{closed:true,error:true}),json=JSON.stringify(summary);assert.equal(summary.submitCount,1);assert.equal(summary.brokerAdmissionCount,1);assert.equal(summary.socketClosed,true);assert.equal(json.includes(privateValue),false)});

test("only an exact correlated tactical stale-basis refusal permits one explicit refresh",()=>{const submit={parentId:"p",basis:{stateSequence:"9",token:"basis"},intent:{actors:[ref(0)]}},value={parentId:"p",basis:submit.basis,childIndex:0,childCount:1,stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",status:"LIVE_RESULT_STATUS_REJECTED",disposition:"LIVE_RESULT_DISPOSITION_RECORDED",reason:"broker refused stale tactical observation basis; refresh the current observation"},rows=[{kind:"result",value}];assert.equal(isExactStaleBasisRefusal(rows,submit),true);for(const change of [{reason:"other refusal"},{stage:"LIVE_RESULT_STAGE_NATIVE_ADMISSION"},{status:"LIVE_RESULT_STATUS_ACCEPTED"},{disposition:"LIVE_RESULT_DISPOSITION_LATE"},{basis:{...submit.basis,stateSequence:"10"}},{parentId:"other"}])assert.equal(isExactStaleBasisRefusal([{kind:"result",value:{...value,...change}}],submit),false);const two={...submit,intent:{actors:[ref(0),ref(1)]}},mixed=[{kind:"result",value:{...value,childCount:2}},{kind:"result",value:{...value,childCount:2,childIndex:1,status:"LIVE_RESULT_STATUS_ACCEPTED"}}];assert.equal(isExactStaleBasisRefusal(mixed,two),false)});
test("fresh correction requires a captured newer basis and new physical parent and input identities",()=>{const stale={parentId:"old-parent",inputId:"old-input",controller:{authorityEpoch:"2"},module:{generation:"4"},basis:basis(9),intent:{action:"build",actors:[ref(0)]}},fresh={...stale,parentId:"new-parent",inputId:"new-input",basis:basis(10)};assert.equal(isFreshPhysicalReplacement(stale,fresh,[{basis:basis(10)}]),true);for(const change of [{parentId:stale.parentId},{inputId:stale.inputId},{controller:{authorityEpoch:"3"}},{module:{generation:"5"}},{basis:basis(9)},{basis:basis(10,"foreign")}])assert.equal(isFreshPhysicalReplacement(stale,{...fresh,...change},[{basis:{...fresh.basis,...change.basis}}]),false);assert.equal(isFreshPhysicalReplacement(stale,fresh,[]),false)});

const basis=(sequence,source="match")=>({matchId:source,processIncarnation:"process",stateChannelIncarnation:"channel",stateSequence:String(sequence),nativeFrame:Number(sequence)});
const liveUnit=(reference,definitionId,health,maxHealth=health)=>({reference,observation:"OBSERVATION_KIND_OWN",definitionId,health,maxHealth});
const observation=(sequence,units,source="match")=>({basis:basis(sequence,source),units:units.map(x=>({reference:x.reference,observation:x.observation})),preview:{units:units.map(x=>({id:x.reference.id,definitionId:x.definitionId,health:x.health,maxHealth:x.maxHealth,position:{x:1,z:2}}))}});
test("causal window excludes foreign source and later unrelated effects",()=>{const before=observation(1,[liveUnit(ref(1),10,10)]),foreign=observation(3,[liveUnit(ref(2),710,10)],"other"),later=observation(9,[liveUnit(ref(3),710,10)]),rows=[{kind:"action",family:"construction",beforeObservation:before},{kind:"submit",value:{parentId:"p",basis:basis(1)}},{kind:"result",value:{parentId:"p",stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",nativeFrame:2}},{kind:"observation",value:foreign},{kind:"action",family:"next",beforeObservation:foreign},{kind:"observation",value:later}];assert.throws(()=>causalActionWindow(rows,"construction"),/bounded later same-source/)});
test("causal window binds effects to the fresh parent after a recorded stale-basis refusal",()=>{const before=observation(1,[liveUnit(ref(1),10,10)]),after=observation(3,[liveUnit(ref(2),710,10)]),rows=[{kind:"action",family:"construction",beforeObservation:before,causalSubmitOrdinal:1},{kind:"submit",value:{parentId:"stale",basis:basis(1)}},{kind:"result",value:{parentId:"stale",stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION"}},{kind:"submit",value:{parentId:"fresh",basis:basis(2)}},{kind:"result",value:{parentId:"fresh",stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",nativeFrame:2}},{kind:"observation",value:after}];assert.equal(causalActionWindow(rows,"construction").submit.parentId,"fresh")});
test("change between refused and fresh inputs is the refreshed baseline, not a fresh-action effect",()=>{const initial=observation(1,[liveUnit(ref(1),10,10)]),intervening=observation(2,[liveUnit(ref(1),10,10),liveUnit(ref(2),710,10)]),unchanged=observation(4,[liveUnit(ref(1),10,10),liveUnit(ref(2),710,10)]),action={kind:"action",family:"construction",beforeObservation:intervening,observationCount:2,causalSubmitOrdinal:1,staleBasisRefresh:{originalBeforeObservation:initial,originalObservationCount:1}},rows=[action,{kind:"submit",value:{parentId:"stale",basis:basis(1)}},{kind:"result",value:{parentId:"stale",stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION"}},{kind:"observation",value:intervening},{kind:"submit",value:{parentId:"fresh",basis:basis(2)}},{kind:"result",value:{parentId:"fresh",stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",nativeFrame:3}},{kind:"observation",value:unchanged}];const window=causalActionWindow(rows,"construction");assert.equal(window.before,intervening);assert.equal(newlyCompletedUnits(window.before,window.last,710).length,0)});
test("unit evidence binds lifetime and rejects preexisting or wrong causal type",()=>{const old=ref(7,"1"),reused=ref(7,"2"),before=observation(1,[liveUnit(old,710,10)]),same=observation(2,[liveUnit(old,710,10)]),reuse=observation(3,[liveUnit(reused,710,10)]),damaged=observation(4,[liveUnit(reused,710,5,10)]);assert.equal(newlyCompletedUnits(before,same,710).length,0);assert.equal(newlyCompletedUnits(before,reuse,710).length,1);assert.equal(exactObservedUnit(reuse,old),undefined);assert.equal(exactObservedUnit(reuse,reused).health,10);assert.equal(exactHealthDecreased(reuse,damaged,reused),true);assert.equal(exactHealthDecreased(reuse,damaged,old),false)});
