import { expect, test } from "@playwright/test";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { closeSync, constants, existsSync, fsyncSync, openSync, readFileSync, writeSync, lstatSync, fstatSync, linkSync, unlinkSync } from "node:fs";
import { createHash, randomBytes } from "node:crypto";
import { pathToFileURL } from "node:url";
import { basename, dirname, resolve, parse, join } from "node:path";
import { assertCanonicalLifecycle, assertObservedEffects, isExactStaleBasisRefusal, isFreshPhysicalReplacement, loadStockSmokeHandoff, loadTacticalHandoff, plannedChildCount, sanitizedLifecycle, waitForTerminalOrClose } from "./tactical-native-evidence.mjs";

import { parseClosedJson, parseStockTraceJsonl } from "./stock-native-trace.mjs";

const enabled=process.env.BARC_RUN_TACTICAL_NATIVE==="1",stockEnabled=process.env.BARC_RUN_STOCK_NATIVE_SMOKE==="1",oneUnitEnabled=process.env.BARC_RUN_ONE_PRODUCED_UNIT==="1";if([enabled,stockEnabled,oneUnitEnabled].filter(Boolean).length>1)throw new Error("native proof routes are mutually exclusive");
const handoff=enabled?await loadTacticalHandoff(process.env.BARC_TACTICAL_HANDOFF):null,stockHandoff=stockEnabled?await loadStockSmokeHandoff(process.env.BARC_STOCK_SMOKE_HANDOFF):null;
let stage,codec;
const oneUnitHandoff=oneUnitEnabled?loadOneUnitHandoff(process.env.BARC_ONE_UNIT_HANDOFF,process.env.BARC_ONE_UNIT_HANDOFF_SHA256):null;
test.beforeAll(async()=>{if(!enabled&&!stockEnabled&&!oneUnitEnabled)return;stage=await mkdtemp(resolve(import.meta.dirname,"node_modules/.barc-tactical-codec-"));await cp(enabled?handoff.codecDirectory:(oneUnitEnabled?oneUnitHandoff.paths.codecDirectory:stockHandoff.paths.codecDirectory),stage,{recursive:true});codec=await import(pathToFileURL(resolve(stage,"codec.js")).href)});
test.afterAll(async()=>{if(stage)await rm(stage,{recursive:true,force:true})});

const key=ref=>`${ref.id}:${ref.lifetime}`, sameRef=(a,b)=>String(a?.id??0)===b.id&&String(a?.lifetime??0)===b.lifetime;
const selector=(kind,ref)=>kind==="feature"?`[data-feature-id="${ref.id}"]`:`[data-unit-id="${ref.id}"][data-lifetime="${ref.lifetime}"]`;
const observations=rows=>rows.filter(x=>x.kind==="observation").map(x=>x.value), latest=rows=>observations(rows).at(-1);
const unit=(o,ref)=>o?.units?.some(x=>sameRef(x.reference,ref))&&o.preview.units.find(x=>String(x.id??0)===ref.id);
const feature=(o,ref)=>o?.tactical?.features?.find(x=>sameRef(x.reference,ref));
const actor=(o,ref)=>o?.tactical?.actors?.find(x=>sameRef(x.actor,ref));
const queue=(o,ref,domain)=>actor(o,ref)?.queue?.find(x=>x.domain===domain);
const near=(a,b,t=64)=>a&&Math.hypot(a.x-b.x,a.z-b.z)<=t;

const startTicks=()=>{const value=readFileSync(`/proc/${process.pid}/stat`,"utf8"),close=value.lastIndexOf(") "),fields=value.slice(close+2).trim().split(/ +/);if(close<0||fields.length<=19)throw new Error("browser writer start identity unavailable");return fields[19]};
function captureJournal(path,release,runId,source,selectedCase="stock-smoke-count1"){
  if(!path||!release||existsSync(path)||existsSync(release))throw new Error("new stock capture/release paths required");const sourcePath=import.meta.filename,writer={pid:process.pid,startTicks:startTicks(),uid:process.geteuid(),executable:process.execPath,sourcePath,sourceSha256:createHash("sha256").update(readFileSync(sourcePath)).digest("hex")},fd=openSync(path,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_APPEND|constants.O_CLOEXEC,0o600);let sequence=0,closed=false;
  const append=(kind,value)=>{if(closed)throw new Error("stock capture already completed");sequence++;writeSync(fd,`${JSON.stringify({schema:"fsbar.barc-stock-browser-capture/v1",runId,sequence:String(sequence),kind,writer,source,value})}\n`)};append("header",{selectedCase});
  return{append,complete(){append("complete",{selectedCase});fsyncSync(fd);closed=true},async hold(){await expect.poll(()=>existsSync(release),{timeout:30000,intervals:[25,50,100,250]}).toBe(true)},close(){closeSync(fd)}};
}
// Readiness controls execute this exact source block without loading native handoffs.
const pairingState=()=>({observed:false,authSentCount:0,bootstrapDecodedCount:0,decodeFailureCount:0,clientCloseCount:0,closed:false,error:false,overflow:false});
function notePairing(state,kind){
  if(kind==="socket"){state.observed=true;return}
  const field={auth:"authSentCount",bootstrap:"bootstrapDecodedCount",decode:"decodeFailureCount","clientdecode-bootstrap-close":"clientCloseCount"}[kind];
  if(field){if(state[field]<64)state[field]++;else state.overflow=true}
  else if(kind==="close")state.closed=true;else if(kind==="error")state.error=true;
}
function pairingSummary(state,paired=null){
  const count=name=>state?.observed===true&&Number.isInteger(state[name])&&state[name]>=0&&state[name]<=64?state[name]:null;
  const counts={authSentCount:count("authSentCount"),bootstrapDecodedCount:count("bootstrapDecodedCount"),decodeFailureCount:count("decodeFailureCount"),clientCloseCount:count("clientCloseCount")};
  const known=state?.observed===true&&state.overflow===false&&Object.values(counts).every(x=>x!==null)&&typeof state.closed==="boolean"&&typeof state.error==="boolean";
  return{schema:"fsbar.barc-pairing-diagnostic/v1",nativeAcceptance:false,state:known?"observed":"unknown",...counts,socketClosed:known?state.closed:null,socketError:known?state.error:null,clientCloseClass:counts.clientCloseCount>0?"clientdecode-bootstrap-close":null,paired:typeof paired==="boolean"?paired:null,counterOverflow:state?.overflow===true};
}
function installPairingCloseObserver(){
  const original=WebSocket.prototype.close;
  WebSocket.prototype.close=function(...args){
    if(args[0]===1008&&args[1]==="invalid live frame")try{window.__barcPairingClose("clientdecode-bootstrap-close")?.catch?.(()=>{})}catch{}
    return Reflect.apply(original,this,args);
  };
}
function writePairingDiagnostic(j,state,paired){
  const path=`${j.outputPath}.pairing-diagnostic.json`,parent=dirname(resolve(path)),parsed=parse(parent);let current=parsed.root,fd=null,temp=null;
  try{
    for(const part of parent.slice(parsed.root.length).split("/").filter(Boolean)){current=join(current,part);if(lstatSync(current).isSymbolicLink())throw new Error()}
    const anchor=lstatSync(parent);if(!anchor.isDirectory()||anchor.uid!==process.geteuid()||(anchor.mode&0o777)!==0o700)throw new Error();
    const data=Buffer.from(JSON.stringify(pairingSummary(state,paired))+"\n");if(data.byteLength>4096)throw new Error();
    temp=join(parent,`.barc-pairing-${randomBytes(16).toString("hex")}`);fd=openSync(temp,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW|constants.O_CLOEXEC,0o600);
    const pin=fstatSync(fd);if(!pin.isFile()||pin.uid!==process.geteuid()||(pin.mode&0o777)!==0o600||pin.nlink!==1)throw new Error();
    for(let offset=0;offset<data.length;){const written=writeSync(fd,data,offset,data.length-offset);if(written<=0)throw new Error();offset+=written}fsyncSync(fd);closeSync(fd);fd=null;const finalAnchor=lstatSync(parent);if(anchor.dev!==finalAnchor.dev||anchor.ino!==finalAnchor.ino||finalAnchor.uid!==process.geteuid()||(finalAnchor.mode&0o777)!==0o700)throw new Error();
    linkSync(temp,path);unlinkSync(temp);temp=null;const directory=openSync(parent,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);try{fsyncSync(directory)}finally{closeSync(directory)}
  }catch{throw new Error("private pairing diagnostic refused")}
  finally{if(fd!==null)closeSync(fd);if(temp!==null)try{unlinkSync(temp)}catch{}}
}

const readinessState=()=>({phase:"unrequested",moduleName:null,moduleSha256:null,armCount:0,armSha256:null,controllerCount:0,controllerStage:null,failureCode:null});
const moduleHash=value=>createHash("sha256").update(value).digest("hex");
function safeArmText(value,j){
  let text=String(value??"").slice(0,4096);
  for(const secret of [j.credential,j.expectedSessionId,j.gatewayUrl,j.receiverUrl,j.guestPath])if(secret)text=text.split(secret).join("[redacted]");
  return text.replace(/(?:https?|wss?):\/\/[^\s]+/gi,"[url]").replace(/[A-Za-z0-9+/_=-]{32,}/g,"[identity]").slice(0,512);
}
async function writeArmFailure(live,j,state){
  const fields={};for(const name of ["module","status","authority","diagnostic"])try{fields[name]=safeArmText(await live.locator(`.${name}`).textContent({timeout:500}),j)}catch{fields[name]="unavailable"}
  const value={schema:"fsbar.barc-native-arm-failure/v1",nativeAcceptance:false,readiness:{phase:state.phase,moduleName:safeArmText(state.moduleName,j),moduleSha256:state.moduleSha256,armCount:state.armCount,armSha256:state.armSha256,controllerCount:state.controllerCount,controllerStage:state.controllerStage,failureCode:state.failureCode},ui:fields};
  await writeFile(j.armFailurePath??`${j.outputPath}.arm-failure.json`,JSON.stringify(value)+"\n",{mode:0o600,flag:"wx"});
}
async function loadSelectedGuest(page,live,j,guest,state){
  state.phase="module-requested";
  if(guest==="Imported guest"){
    const data=await readFile(j.guestPath);if(data.byteLength>8*1024*1024){state.failureCode="module-too-large";throw new Error("Imported guest exceeds module bound")};
    state.moduleSha256=moduleHash(data);if(state.moduleSha256!==j.guestSha256){state.failureCode="import-hash-mismatch";throw new Error("Imported guest hash mismatch")}state.moduleName=basename(j.guestPath);
    await live.getByRole("button",{name:"Import .wasm"}).click();await live.locator("[data-file]").setInputFiles(j.guestPath);
  }else{
    const names={"Manual guest":"manual-preview.wasm","Custom guest":"custom-preview.wasm"};state.moduleName=names[guest];if(!state.moduleName)throw new Error("Unknown selected bundled guest");
    // Register before the click: a Playwright click does not await the handler's fetch/body.
    const responsePromise=page.waitForResponse(response=>new URL(response.url()).pathname.endsWith(`/guests/${state.moduleName}`),{timeout:5000});
    const [response]=await Promise.all([responsePromise,live.getByRole("button",{name:guest}).click()]);
    if(!response.ok()){state.failureCode="module-download-unavailable";throw new Error("Selected bundled guest download unavailable")}
    const data=await response.body();if(data.byteLength>8*1024*1024){state.failureCode="module-too-large";throw new Error("Bundled guest exceeds module bound")};state.moduleSha256=moduleHash(data);
    if(j.bundledGuestSha256&&state.moduleSha256!==j.bundledGuestSha256){state.failureCode="bundled-hash-mismatch";throw new Error("Bundled guest hash mismatch")}
  }
  await expect(live.locator(".module")).toHaveText(`${state.moduleName} — not armed`);
  state.phase="module-ready";
}
// End readiness source block.
async function capture(page,journal=null){const rows=[],connection={closed:false,error:false},readiness=readinessState(),pairing=pairingState();Object.defineProperties(rows,{connection:{value:connection},readiness:{value:readiness},pairing:{value:pairing}});await page.exposeBinding("__barcPairingClose",(_,code)=>{if(code==="clientdecode-bootstrap-close")notePairing(pairing,code)});await page.addInitScript(installPairingCloseObserver);const retain=row=>{rows.push(row);journal?.append(row.kind,row.value)};page.on("websocket",socket=>{notePairing(pairing,"socket");socket.on("framesent",event=>{try{const e=codec.canonicalObject(codec.v1.LiveClientEnvelope,Uint8Array.from(event.payload));if(e.body==="authenticate")notePairing(pairing,"auth");if(e.body==="arm"){readiness.armCount++;const hash=Buffer.from(e.arm.module?.sha256??"","base64");readiness.armSha256=hash.length===32?hash.toString("hex"):null}if(e.body==="submit")retain({direction:"client",kind:"submit",value:e.submit})}catch{}});socket.on("framereceived",event=>{try{const e=codec.canonicalObject(codec.v1.LiveServerEnvelope,Uint8Array.from(event.payload));if(e.body==="bootstrap")notePairing(pairing,"bootstrap");if(e.body==="controllerState"){readiness.controllerCount++;const stage=e.controllerState.stage;readiness.controllerStage=/^CONTROLLER_STAGE_[A-Z_]{1,40}$/.test(stage)?stage:"invalid"}if(["result","observation","controllerState"].includes(e.body))retain({direction:"server",kind:e.body,value:e[e.body]})}catch{notePairing(pairing,"decode")}});socket.on("close",()=>{connection.closed=true;notePairing(pairing,"close")});socket.on("socketerror",()=>{connection.error=true;notePairing(pairing,"error")})});return rows}
async function pair(page,j,guest="Manual guest",rows){
  const live=page.locator(".barc-preview.barc-live"),state=rows.readiness;let pairingFailed=false;
  try{
    await page.goto(j.receiverUrl);await live.getByLabel("Gateway").fill(j.gatewayUrl);await live.getByLabel("Session UUID").fill(j.expectedSessionId);await live.getByLabel("One-time credential").fill(j.credential);await live.getByRole("button",{name:"Pair"}).click();
    await expect(live.locator(".catalogue")).not.toContainText("unavailable");await expect(live.locator(".economy")).toContainText("Economy");
    await loadSelectedGuest(page,live,j,guest,state);
    if(j.deferArm)return live;
    state.phase="arm-clicked";await live.getByRole("button",{name:"Arm live"}).click();
    await expect.poll(()=>state.armSha256).toBe(state.moduleSha256);await expect(live.locator(".authority")).toContainText("arm native confirmed");state.phase="native-confirmed";return live;
  }catch(error){pairingFailed=true;state.failureCode??=state.phase==="arm-clicked"?"authority-not-confirmed":"pair-or-module-not-ready";await writeArmFailure(live,j,state);throw error}
  finally{let paired=null;try{paired=(await live.locator(".status").textContent({timeout:500}))==="current: live session"}catch{}try{writePairingDiagnostic(j,rows.pairing,paired)}catch(error){if(!pairingFailed)throw error}}
}
async function target(live,p){await live.getByLabel("Target X").fill(String(p.x));await live.getByLabel("Target Z").fill(String(p.z))}
async function keyboardSelect(page,live,refs){const map=live.getByLabel(/Live tactical map/);await map.focus();for(let i=0;i<64&&!((await live.locator(".selection").textContent())??"").includes(key(refs[0]));i++)await page.keyboard.press("Tab");expect(await live.locator(".selection").textContent()).toContain(key(refs[0]));for(const ref of refs.slice(1)){for(let i=0;i<64&&!((await live.locator(".selection").textContent())??"").includes(key(ref));i++)await page.keyboard.press("Control+Tab");expect(await live.locator(".selection").textContent()).toContain(key(ref))}}
const selectedRefs=async live=>{const value=(await live.locator(".selection").textContent())??"",match=/^Actors (.*?) ·/.exec(value);return match?match[1].split(", "):[]}
async function actorPoint(live,ref){
  const actor=live.locator(selector("unit",ref));let point=null;
  await expect.poll(async()=>{
    point=await actor.evaluate((node,expected)=>{
      if(!node.isConnected||node.dataset.unitId!==expected.id||node.dataset.lifetime!==expected.lifetime)return null;
      node.scrollIntoView({block:"center",inline:"center"});
      const box=node.getBoundingClientRect(),x=box.left+box.width/2,y=box.top+box.height/2;
      return box.width>0&&box.height>0&&Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&y>=0&&x<innerWidth&&y<innerHeight?{x,y}:null;
    },ref).catch(()=>null);
    return point;
  },{timeout:30000,intervals:[0,10,25,50,100,250]}).not.toBeNull();
  return point;
}
async function pointerSelect(page,live,ref,expected,toggle=false){for(let attempt=0;attempt<64;attempt++){const point=await actorPoint(live,ref);if(toggle)await page.keyboard.down("Control");try{await page.mouse.click(point.x,point.y)}finally{if(toggle)await page.keyboard.up("Control")}if(JSON.stringify(await selectedRefs(live))===JSON.stringify(expected.map(key)))return}throw new Error(`pointer could not establish exact actor set ${expected.map(key).join(", ")}`)}
async function select(page,live,source,refs){if(source==="keyboard")return keyboardSelect(page,live,refs);for(let i=0;i<refs.length;i++)await pointerSelect(page,live,refs[i],refs.slice(0,i+1),i>0)}
async function cycleTarget(page,live,kind,ref){const map=live.getByLabel(/Live tactical map/),letter=kind==="friendly"?"t":"f",label=kind==="friendly"?"Friendly":"Feature";await map.focus();for(let i=0;i<64&&!((await live.locator(".target").textContent())??"").includes(`${label} ${key(ref)}`);i++)await page.keyboard.press(letter);expect(await live.locator(".target").textContent()).toContain(`${label} ${key(ref)}`)}
async function setFriendly(page,live,source,ref){if(source==="keyboard")return cycleTarget(page,live,"friendly",ref);const before=await selectedRefs(live);for(let attempt=0;attempt<64;attempt++){const point=await actorPoint(live,ref);await page.keyboard.down("Shift");try{await page.mouse.click(point.x,point.y)}finally{await page.keyboard.up("Shift")}expect(await selectedRefs(live)).toEqual(before);if(((await live.locator(".target").textContent())??"").includes(`Friendly ${key(ref)}`))return}throw new Error(`pointer could not reach friendly actor ${key(ref)} through overlapping map targets`)}
async function setFeature(page,live,source,ref){if(source==="keyboard")await cycleTarget(page,live,"feature",ref);else await live.locator(selector("feature",ref)).click()}

const terminal=value=>value.status==="LIVE_RESULT_STATUS_REJECTED"||value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"||value.stage==="LIVE_RESULT_STAGE_UNKNOWN";
async function settleSubmit(rows,submit,expectation="applied"){
  const count=plannedChildCount(submit.intent);await waitForTerminalOrClose(rows,rows.connection,submit.parentId,count);
  const values=rows.filter(x=>x.kind==="result"&&x.value.parentId===submit.parentId),applied=values.filter(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_APPLIED");
  if(expectation==="applied")expect(applied).toHaveLength(count);else if(expectation==="broker-refused"){expect(applied).toHaveLength(0);expect(values).toHaveLength(count);expect(values.every(x=>x.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_REJECTED"&&x.value.disposition==="LIVE_RESULT_DISPOSITION_RECORDED"&&JSON.stringify(x.value.basis)===JSON.stringify(submit.basis))).toBeTruthy()}else if(expectation==="native-refused"){expect(applied).toHaveLength(0);expect(values.filter(x=>x.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_ACCEPTED")).toHaveLength(count);expect(values.some(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_REJECTED"||x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_SKIPPED")).toBeTruthy()}else{expect(applied.length).toBeGreaterThan(0);expect(applied.length).toBeLessThan(count);expect(values.filter(x=>x.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_ACCEPTED")).toHaveLength(count)}return submit;
}
async function waitEffect(rows,action,predicate){await expect.poll(()=>observations(rows).slice(action.observationCount).find(o=>predicate(action.beforeObservation,o))?.basis?.stateSequence??null,{timeout:120000}).not.toBeNull();const hit=observations(rows).slice(action.observationCount).find(o=>predicate(action.beforeObservation,o));action.effectObservationSequence=hit.basis.stateSequence;return hit}
async function physicalSubmit(page,live,source){if(source==="pointer")await live.getByRole("button",{name:"Send tactical command"}).click();else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("Enter")}}
async function trigger(page,live,rows,source,family,{expectation="applied",effect}={}){
  const before=rows.filter(x=>x.kind==="submit").length,action={kind:"action",family,source,beforeObservation:latest(rows),observationCount:observations(rows).length};rows.push(action);await physicalSubmit(page,live,source);await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+1);let submit=rows.filter(x=>x.kind==="submit")[before].value;
  const count=plannedChildCount(submit.intent);await waitForTerminalOrClose(rows,rows.connection,submit.parentId,count);
  if(expectation==="applied"&&isExactStaleBasisRefusal(rows,submit)){
    const staleSequence=BigInt(submit.basis.stateSequence);action.submitCount=2;action.causalSubmitOrdinal=1;action.staleBasisRefresh={rejectedStateSequence:submit.basis.stateSequence,originalBeforeObservation:action.beforeObservation,originalObservationCount:action.observationCount};
    await expect(live.locator(".result")).toContainText("LIVE_RESULT_STAGE_BROKER_ADMISSION: LIVE_RESULT_STATUS_REJECTED");
    await expect.poll(()=>BigInt(latest(rows)?.basis?.stateSequence??0)>staleSequence,{timeout:30000}).toBe(true);
    action.beforeObservation=latest(rows);action.observationCount=observations(rows).length;
    await physicalSubmit(page,live,source);await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+2);submit=rows.filter(x=>x.kind==="submit")[before+1].value;
    expect(isFreshPhysicalReplacement(rows.filter(x=>x.kind==="submit")[before].value,submit,observations(rows))).toBeTruthy();action.staleBasisRefresh.freshStateSequence=submit.basis.stateSequence;
  }
  await settleSubmit(rows,submit,expectation);if(effect)await waitEffect(rows,action,effect);return{submit,action};
}

async function exerciseManual(page,j,rows,source){
  const live=await pair(page,j,"Manual guest",rows),descriptor=(ref,kind)=>actor(latest(rows),ref)?.descriptors?.some(x=>x.kind===kind&&!x.disabled);
  const reclaimed=(before,o,predicate)=>{const a=before.tactical?.economy?.metal,b=o.tactical?.economy?.metal;if(!predicate(o)||!Number.isFinite(a?.current)||!Number.isFinite(b?.current))return false;const seconds=Math.max(0,(Number(o.preview.capturedAtUnixMs)-Number(before.preview.capturedAtUnixMs))/1000);return b.current-a.current>(a.incomePerSecond??0)*seconds+(j.resourceAttributionTolerance??0.01)};
  await select(page,live,source,[j.builder]);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await live.getByLabel("Facing").selectOption("BUILD_FACING_SOUTH");const beforeBuild=new Set(latest(rows).units.map(x=>key(x.reference)));await trigger(page,live,rows,source,"construction",{effect:(_,o)=>o.units.some(x=>!beforeBuild.has(key(x.reference))&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)})?.definitionId===j.buildDefinitionId&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).health>=unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).maxHealth)});rows.push({kind:"action",family:"economy",source,noSubmit:true,beforeObservation:latest(rows)});
  for(const[family,actionKind,targetRef,keyName]of[["guard","guard",j.repairTarget,"g"],["repair","repair",j.repairTarget,"r"],["reclaimUnit","reclaimUnit",j.reclaimUnitTarget,"l"]]){await select(page,live,source,[j.builder]);await setFriendly(page,live,source,targetRef);if(source==="keyboard"){await live.getByLabel(/Live tactical map/).focus();await page.keyboard.press(keyName)}else await live.getByLabel("Action").selectOption(actionKind);const before=latest(rows),health=unit(before,targetRef)?.health;await trigger(page,live,rows,source,family,{effect:(_,o)=>family==="guard"?queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>e.action==="LIVE_ACTION_KIND_GUARD"&&sameRef(e.unitTarget,targetRef)):family==="repair"?unit(o,targetRef)?.health>health:reclaimed(before,o,x=>!unit(x,targetRef)||unit(x,targetRef).health<health)})}
  await select(page,live,source,[j.builder]);await setFeature(page,live,source,j.feature);if(source==="keyboard"){await live.getByLabel(/Live tactical map/).focus();await page.keyboard.press("x")}const featureStart=latest(rows),featureBefore=feature(featureStart,j.feature)?.reclaimLeft;await trigger(page,live,rows,source,"reclaimFeature",{effect:(_,o)=>reclaimed(featureStart,o,x=>!feature(x,j.feature)||feature(x,j.feature).reclaimLeft<featureBefore)});
  await select(page,live,source,[j.builder]);await target(live,j.positions.reclaim);await live.getByLabel("Action").selectOption("reclaimArea");const areaStart=latest(rows),areaBefore=feature(areaStart,j.areaFeature)?.reclaimLeft;await trigger(page,live,rows,source,"reclaimArea",{effect:(_,o)=>reclaimed(areaStart,o,x=>!feature(x,j.areaFeature)||feature(x,j.areaFeature).reclaimLeft<areaBefore)});

  await select(page,live,source,[j.factory]);await target(live,j.positions.rally);await live.getByLabel("Action").selectOption("setRally");const rallyRev=queue(latest(rows),j.factory,"QUEUE_DOMAIN_FACTORY_RALLY")?.revision;await trigger(page,live,rows,source,"rally",{effect:(_,o)=>queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_RALLY")?.revision!==rallyRev});
  await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Definition").selectOption(String(j.existingProductionDefinitionId));await live.getByLabel("Count").fill("1");await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_APPEND");await trigger(page,live,rows,source,"factoryAppendSeed",{effect:(_,o)=>{const value=queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");return value?.complete&&value.repeat===false&&value.entries?.length>0&&Number(value.entries[0].definitionId)===j.existingProductionDefinitionId}});
  await live.getByLabel("Definition").selectOption(String(j.productDefinitionId));await live.getByLabel("Count").fill(String(j.productionCount));const beforeProducts=new Set(latest(rows).units.map(x=>key(x.reference)));const factory=await trigger(page,live,rows,source,"factoryAppendQuantity",{effect:(_,o)=>{const made=o.units.filter(x=>!beforeProducts.has(key(x.reference))&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)})?.definitionId===j.productDefinitionId);return made.length===Number(j.productionCount)&&made.every(x=>near(unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).position,j.positions.rally,j.rallyTolerance??64))}});expect(plannedChildCount(factory.submit.intent)).toBe(Number(j.productionCount));
  await live.getByLabel("Definition").selectOption(String(j.existingProductionDefinitionId));await live.getByLabel("Count").fill("1");await trigger(page,live,rows,source,"factoryReplaceSeed",{effect:(_,o)=>{const value=queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");return value?.complete&&value.repeat===false&&value.entries?.length>0&&Number(value.entries[0].definitionId)===j.existingProductionDefinitionId}});await live.getByLabel("Definition").selectOption(String(j.productDefinitionId));await live.getByLabel("Count").fill(String(j.productionCount));await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REPLACE");const replaceBefore=latest(rows),replaceQueue=structuredClone(queue(replaceBefore,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")),replaceRally=structuredClone(queue(replaceBefore,j.factory,"QUEUE_DOMAIN_FACTORY_RALLY")),replace=await trigger(page,live,rows,source,"factoryReplaceNonemptySafety",{expectation:"broker-refused"});await expect.poll(()=>{const value=latest(rows);return BigInt(value?.basis?.stateSequence??0)>BigInt(replace.submit.basis.stateSequence)&&JSON.stringify(queue(value,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION"))===JSON.stringify(replaceQueue)&&JSON.stringify(queue(value,j.factory,"QUEUE_DOMAIN_FACTORY_RALLY"))===JSON.stringify(replaceRally)},{timeout:30000}).toBe(true);replace.action.safetyObservationSequence=latest(rows).basis.stateSequence;await expect.poll(()=>queue(latest(rows),j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.entries?.length??-1,{timeout:120000}).toBe(0);
  await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_FACTORY_PRODUCTION");await live.getByLabel("Action").selectOption("queueEdit");expect(queue(latest(rows),j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.entries).toHaveLength(0);await live.getByLabel("Queue operation").selectOption("repeat-on");await trigger(page,live,rows,source,"queueRepeat",{effect:(_,o)=>queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.repeat===true});await live.getByLabel("Queue operation").selectOption("repeat-off");await trigger(page,live,rows,source,"queueRepeatOff",{effect:(_,o)=>queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.repeat===false});

  await select(page,live,source,[j.builder]);await live.getByLabel("Action").selectOption("queueEdit");await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_ACTOR_ORDER");await live.getByLabel("Queue operation").selectOption("insert");const insertRev=queue(latest(rows),j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.revision;const inserted=await trigger(page,live,rows,source,"queueInsert",{effect:(_,o)=>queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.revision!==insertRev&&queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.length>0});const tag=queue(latest(rows),j.builder,"QUEUE_DOMAIN_ACTOR_ORDER").entries[0].nativeTag;expect(Number(tag)).toBeGreaterThan(0);inserted.action.observedNativeTag=String(tag);
  await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REJECT_IF_BUSY");await trigger(page,live,rows,source,"rejectBusy",{expectation:"native-refused"});await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REPLACE");
  await live.getByLabel("Action").selectOption("queueEdit");await live.getByLabel("Queue operation").selectOption("remove");const removed=await trigger(page,live,rows,source,"queueRemove",{effect:(_,o)=>!queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>String(e.nativeTag)===String(tag))});removed.action.observedNativeTag=String(tag);
  await live.getByLabel("Queue operation").selectOption("insert");await trigger(page,live,rows,source,"queueInsertForStale",{effect:(_,o)=>queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.length>0});await live.getByLabel("Queue operation").selectOption("remove");const staleTag=String(queue(latest(rows),j.builder,"QUEUE_DOMAIN_ACTOR_ORDER").entries[0].nativeTag),staleBefore=rows.filter(x=>x.kind==="submit").length,stale={kind:"action",family:"staleRevision",source,submitCount:2,beforeObservation:latest(rows),observationCount:observations(rows).length,observedNativeTag:staleTag};rows.push(stale);const control=source==="pointer"?live.getByRole("button",{name:"Send tactical command"}):live.getByLabel(/Live tactical map/);await control.evaluate((node,keyboard)=>{if(keyboard){node.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}));node.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}))}else{node.click();node.click()}},source==="keyboard");await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(staleBefore+2);const staleSubmits=rows.filter(x=>x.kind==="submit").slice(staleBefore,staleBefore+2).map(x=>x.value);expect(staleSubmits[0].basis).toEqual(staleSubmits[1].basis);expect(staleSubmits[0].intent.actorTacticalBindings).toEqual(staleSubmits[1].intent.actorTacticalBindings);await settleSubmit(rows,staleSubmits[0],"applied");await settleSubmit(rows,staleSubmits[1],"native-refused");await waitEffect(rows,stale,(_,o)=>!queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>String(e.nativeTag)===staleTag));

  for(const[family,kind,ref]of[["barConstructionPriority","TACTICAL_DESCRIPTOR_BAR_CONSTRUCTION_PRIORITY",j.modeActors.constructionPriority],["barCloakDesire","TACTICAL_DESCRIPTOR_BAR_CLOAK_DESIRE",j.modeActors.cloakDesire]]){expect(descriptor(ref,kind)).toBeTruthy();await select(page,live,source,[ref]);await live.getByLabel("Action").selectOption("tacticalMode");await live.getByLabel("Mode").selectOption(kind);await live.getByLabel("Mode value").selectOption("TACTICAL_MODE_VALUE_ENABLED");await trigger(page,live,rows,source,family,{effect:(_,o)=>actor(o,ref)?.descriptors?.some(d=>d.kind===kind&&d.observedModeValue==="TACTICAL_MODE_VALUE_ENABLED")})}
  await select(page,live,source,j.mixedActors);await setFriendly(page,live,source,j.repairTarget);await live.getByLabel("Action").selectOption(j.mixedAction);const mixed=await trigger(page,live,rows,source,"mixedChildren",{expectation:"mixed",effect:(_,o)=>queue(o,j.mixedAppliedActor,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>e.action==="LIVE_ACTION_KIND_GUARD"&&sameRef(e.unitTarget,j.repairTarget))});expect(mixed.submit.intent.actors.map(x=>key({id:String(x.id??0),lifetime:String(x.lifetime)}))).toEqual(j.mixedActors.map(key));const mixedRows=rows.filter(x=>x.kind==="result"&&x.value.parentId===mixed.submit.parentId),forActor=ref=>mixedRows.filter(x=>sameRef(x.value.actor,ref));expect(forActor(j.mixedAppliedActor).some(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_APPLIED")).toBeTruthy();expect(forActor(j.mixedRefusedActor).some(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_REJECTED"||x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_SKIPPED")).toBeTruthy();
  await select(page,live,source,[j.builder]);const health=unit(latest(rows),j.combatTarget)?.health,before=rows.filter(x=>x.kind==="submit").length,action={kind:"action",family:"combat",source,beforeObservation:latest(rows),observationCount:observations(rows).length};rows.push(action);if(source==="pointer")await live.locator(selector("unit",j.combatTarget)).click();else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("a");await page.keyboard.press("Enter")}await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+1);await settleSubmit(rows,rows.filter(x=>x.kind==="submit")[before].value,"applied");await waitEffect(rows,action,(_,o)=>unit(o,j.combatTarget)?.health<health);
}

async function imported(page,j,rows){const live=await pair(page,j,"Imported guest",rows);await select(page,live,"pointer",j.importedActors);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));const ids=new Set(latest(rows).units.map(x=>key(x.reference)));await trigger(page,live,rows,"pointer","importedPolicyEffect",{effect:(_,o)=>o.units.some(x=>!ids.has(key(x.reference))&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)})?.definitionId===j.buildDefinitionId&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).health>=unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).maxHealth)});const before=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family:"zeroWriteRefusal",source:"pointer",noSubmit:true,beforeObservation:latest(rows)});await live.getByLabel("Action").selectOption(j.unavailableAction??"setRally");await live.getByRole("button",{name:"Send tactical command"}).click({force:true});await page.waitForTimeout(250);expect(rows.filter(x=>x.kind==="submit")).toHaveLength(before)}

test.describe("actual tactical BAR receiver",()=>{test.skip(!enabled,"requires parent-owned tactical native handoff");for(const product of handoff?.products??[])for(const journey of product.journeys)test(`${product.id} ${journey.mode} reaches fenced tactical effects`,async({page})=>{const rows=await capture(page);try{if(journey.mode==="pointer")await exerciseManual(page,journey,rows,"pointer");else if(journey.mode==="keyboard")await exerciseManual(page,journey,rows,"keyboard");else await imported(page,journey,rows);const planned=[];let active=null,remaining=0,ordinal=0;for(const row of rows){if(row.kind==="action"&&!row.noSubmit){active=row;remaining=row.submitCount??1;ordinal=0}else if(row.kind==="submit"){planned.push({submit:row.value,action:active,family:active?.family,ordinal:ordinal++});if(--remaining<=0)active=null}}const parents=planned.map(({submit,action,family,ordinal})=>{const refreshed=action?.causalSubmitOrdinal===1;if(refreshed&&ordinal===0)expect(isExactStaleBasisRefusal(rows,submit)).toBeTruthy();return{id:submit.parentId,childCount:plannedChildCount(submit.intent),requireApplied:refreshed?ordinal===1:!["rejectBusy","mixedChildren","factoryReplaceNonemptySafety"].includes(family)&&(family!=="staleRevision"||ordinal===0),requireNonApplied:refreshed?ordinal===0:["rejectBusy","factoryReplaceNonemptySafety"].includes(family)||(family==="staleRevision"&&ordinal===1),requireMixed:family==="mixedChildren"}}),stages={LIVE_RESULT_STAGE_BROKER_ADMISSION:"BrokerAdmission",LIVE_RESULT_STAGE_NATIVE_ADMISSION:"NativeAdmission",LIVE_RESULT_STAGE_NATIVE_DISPATCH:"NativeDispatch",LIVE_RESULT_STAGE_UNKNOWN:"Unknown"},statuses={LIVE_RESULT_STATUS_ACCEPTED:"Accepted",LIVE_RESULT_STATUS_REJECTED:"Rejected",LIVE_RESULT_STATUS_APPLIED:"Applied",LIVE_RESULT_STATUS_SKIPPED:"Skipped",LIVE_RESULT_STATUS_EXPIRED:"Expired",LIVE_RESULT_STATUS_UNKNOWN:"Unknown"},results=rows.filter(x=>x.kind==="result").map(x=>({kind:"result",parentId:x.value.parentId,childIndex:x.value.childIndex,childCount:x.value.childCount,stage:stages[x.value.stage],status:statuses[x.value.status]}));assertCanonicalLifecycle(results,parents);const coverage=assertObservedEffects(rows,journey);if(journey.mode!=="importedGuest")rows.push({kind:"coverage",value:coverage});await writeFile(journey.outputPath,rows.map(row=>JSON.stringify(row)).join("\n")+"\n",{mode:0o600,flag:"wx"})}catch(error){await writeFile(`${journey.outputPath}.partial.json`,JSON.stringify(sanitizedLifecycle(rows,rows.connection))+"\n",{mode:0o600,flag:"wx"});throw error}})});

test.describe("selected stock Count1 smoke",()=>{
  test.skip(!stockEnabled,"requires root-admitted selected stock smoke handoff");
  test("uses the production browser path and retains exact stock trace joins",async({page})=>{
    const h=stockHandoff,capturePath=process.env.BARC_STOCK_SMOKE_CAPTURE,releasePath=process.env.BARC_STOCK_SMOKE_RELEASE;if(capturePath!==h.paths.capture)throw new Error("authenticated capture path changed");const journal=captureJournal(capturePath,releasePath,h.runId,h.source),j={receiverUrl:h.connection.receiverUrl,gatewayUrl:h.connection.gatewayUrl,allowedOrigin:h.connection.allowedOrigin,expectedSessionId:h.connection.sessionId,credential:h.connection.credential,bundledGuestSha256:h.artifacts.guest.sha256,outputPath:capturePath,armFailurePath:`${capturePath}.arm-failure.json`};
    try{const rows=await capture(page,journal),live=await pair(page,j,"Manual guest",rows);await expect.poll(()=>latest(rows)?.basis?.stateSequence??null,{timeout:30000}).not.toBeNull();await select(page,live,"pointer",[h.actors.factory]);const initial=queue(latest(rows),h.actors.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");expect(initial?.complete).toBe(true);expect(initial?.evidenceScheme).toBe("NATIVE_QUEUE_EVIDENCE_SCHEME_STOCK_LUA_SUPPORTED_FIELDS_V1");expect(initial?.entries?.length).toBeGreaterThan(0);
      await target(live,h.setup.positions.rally);await live.getByLabel("Action").selectOption("setRally");await trigger(page,live,rows,"pointer","stockSmokeRally");await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Definition").selectOption(String(h.setup.productDefinitionId));await live.getByLabel("Count").fill("1");await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_APPEND");const append=await trigger(page,live,rows,"pointer","stockSmokeAppend1");expect(plannedChildCount(append.submit.intent)).toBe(1);
      const beforeReplace=rows.filter(row=>row.kind==="submit").length;await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REPLACE");await live.getByRole("button",{name:"Send tactical command"}).click();await expect(live.locator(".result")).toContainText("No Append fallback");await page.waitForTimeout(250);expect(rows.filter(row=>row.kind==="submit")).toHaveLength(beforeReplace);journal.append("ui-refusal",{action:"factoryProduce",queuePolicy:"TACTICAL_QUEUE_POLICY_REPLACE",submitCountBefore:beforeReplace,submitCountAfter:beforeReplace,detail:"No Append fallback"});
      await select(page,live,"pointer",[h.actors.builder]);await target(live,h.setup.positions.move);const beforeMove=rows.filter(row=>row.kind==="submit").length;await live.getByRole("button",{name:"Move"}).click();await expect.poll(()=>rows.filter(row=>row.kind==="submit").length,{timeout:30000}).toBe(beforeMove+1);await settleSubmit(rows,rows.filter(row=>row.kind==="submit")[beforeMove].value,"applied");const beforeAttack=rows.filter(row=>row.kind==="submit").length;await live.locator(selector("unit",h.actors.combatTarget)).click();await expect.poll(()=>rows.filter(row=>row.kind==="submit").length,{timeout:30000}).toBe(beforeAttack+1);await settleSubmit(rows,rows.filter(row=>row.kind==="submit")[beforeAttack].value,"applied");journal.complete();await journal.hold();
    }finally{journal.close()}
  });
});


// ONE_UNIT_SOURCE_BEGIN: dedicated proof, never a smoke or full-six alias.
const oneUnitCase="selected stock one-unit";
const insistOne=(condition,message)=>{if(!condition)throw new Error(`one-unit refused: ${message}`)};
const closedOne=(value,keys,label)=>insistOne(value&&typeof value==="object"&&!Array.isArray(value)&&JSON.stringify(Object.keys(value).sort())===JSON.stringify([...keys].sort()),`${label} keys changed`);
function loadOneUnitHandoff(path,sha256){
  insistOne(typeof path==="string"&&path.startsWith("/")&&/^[a-f0-9]{64}$/.test(sha256??""),"pinned handoff required");
  const st=lstatSync(path),bytes=readFileSync(path);insistOne(st.isFile()&&!st.isSymbolicLink()&&st.nlink===1&&(st.mode&0o777)===0o600&&bytes.length<=65536&&createHash("sha256").update(bytes).digest("hex")===sha256,"handoff physical/body pin changed");
  const h=parseClosedJson(bytes.toString("utf8"));closedOne(h,["schema","runId","selectedCase","source","paths","connection","artifacts","actors","setup","attribution"],"handoff");
  insistOne(h.schema==="fsbar.barc-one-produced-unit-handoff/v1"&&h.selectedCase===oneUnitCase,"closed selected case required");
  closedOne(h.source,["fsbarCommit","highbarCommit"],"source");insistOne(Object.values(h.source).every(x=>/^[a-f0-9]{40}$/.test(x)),"exact source commits required");
  closedOne(h.connection,["receiverUrl","gatewayUrl","allowedOrigin","sessionId","credential"],"connection");const receiver=new URL(h.connection.receiverUrl),gateway=new URL(h.connection.gatewayUrl),origin=new URL(h.connection.allowedOrigin);insistOne(receiver.protocol==="http:"&&origin.protocol==="http:"&&gateway.protocol==="ws:"&&[receiver,origin,gateway].every(u=>u.hostname==="127.0.0.1"&&!u.username&&!u.password&&!u.hash)&&receiver.origin===origin.origin&&/^[a-f0-9]{64}$/.test(h.connection.credential),"exact private loopback connection required");
  closedOne(h.artifacts,["guest"],"artifacts");closedOne(h.artifacts.guest,["path","sha256"],"guest");insistOne(/^[a-f0-9]{64}$/.test(h.artifacts.guest.sha256),"actual produced guest digest required");
  closedOne(h.paths,["codecDirectory","capture","release","nativeEvents","stockTrace","eventQualification"],"paths");
  insistOne(Object.values(h.paths).every(p=>typeof p==="string"&&p.startsWith("/")),"absolute capsule paths required");
  closedOne(h.attribution,["qualified","qualificationSha256","writer","acceptedGeneration","processIncarnation","stateChannelIncarnation"],"attribution");
  insistOne(h.attribution.qualified===true&&/^[a-f0-9]{64}$/.test(h.attribution.qualificationSha256),"actual event-source qualification missing");
  const qualification=readFileSync(h.paths.eventQualification);insistOne(qualification.length<=65536&&createHash("sha256").update(qualification).digest("hex")===h.attribution.qualificationSha256,"event-source qualification body changed");
  const qualified=parseClosedJson(qualification.toString("utf8"));insistOne(qualified.schema==="bar.one-unit-attribution-source-qualification/v1"&&qualified.actualPassed===true&&qualified.acceptedGeneration===h.attribution.acceptedGeneration&&qualified.noAutonomousOrders===true&&qualified.runId===h.runId&&JSON.stringify(qualified.source)===JSON.stringify(h.source)&&JSON.stringify(qualified.writer)===JSON.stringify(h.attribution.writer)&&qualified.processIncarnation===h.attribution.processIncarnation&&qualified.stateChannelIncarnation===h.attribution.stateChannelIncarnation&&/^[a-f0-9]{64}$/.test(qualified.noAutonomousConfigurationEvidenceSha256??""),"genuine qualified run/source/writer/generation/no-autonomous configuration missing");
  closedOne(h.actors,["factory"],"actors");closedOne(h.setup,["productDefinitionId","seedDefinitionId","maximumSeconds"],"setup");
  insistOne(h.setup.maximumSeconds===180&&Number.isInteger(h.setup.productDefinitionId)&&h.setup.productDefinitionId>0&&Number.isInteger(h.setup.seedDefinitionId)&&h.setup.seedDefinitionId>0&&h.setup.seedDefinitionId!==h.setup.productDefinitionId,"finite distinct seed/product setup required");
  // Missing capture-source or native feed refuses before browser pairing/Arm.
  insistOne(existsSync(h.paths.nativeEvents),"genuine native event feed missing");return h;
}
function nativeOneEvents(h,rows,before){
  const st=lstatSync(h.paths.nativeEvents);insistOne(st.isFile()&&!st.isSymbolicLink()&&st.nlink===1&&st.size<=4*1024*1024,"native event stream physical bound changed");
  const text=readFileSync(h.paths.nativeEvents,"utf8"),lines=text.split("\n");lines.pop();insistOne(lines.length>0&&lines.length<=8192,"native event row bound changed");
  const raw=lines.map((line,index)=>{insistOne(Buffer.byteLength(line)<=32768,"native event record oversized");const r=parseClosedJson(line);closedOne(r,["schema","runId","sequence","kind","writer","source","acceptedGeneration","stateSequence","nativeFrame","disposition","value"],"native raw row");insistOne(r.schema==="fsbar.barc-one-unit-raw-state-journal/v1"&&r.runId===h.runId&&r.sequence===String(index+1)&&JSON.stringify(r.writer)===JSON.stringify(h.attribution.writer)&&JSON.stringify(r.source)===JSON.stringify(h.source)&&r.acceptedGeneration===h.attribution.acceptedGeneration,"native raw origin/generation/sequence changed");insistOne(["snapshot","unit-created","unit-finished","command-dispatch"].includes(r.kind)&&["materialized","invalidated","gap","liveness-only"].includes(r.disposition)&&/^[0-9]+$/.test(r.stateSequence)&&Number.isSafeInteger(r.nativeFrame)&&r.nativeFrame>=0,"unknown native event or basis");return r});
  // Freeze the pre-Arm baseline by its actual browser/native state position.
  const snapshot=raw.find(r=>r.kind==="snapshot"&&r.disposition==="materialized"&&r.stateSequence===before.basis.stateSequence&&r.nativeFrame===Number(before.basis.nativeFrame));insistOne(snapshot,"actual same-basis baseline snapshot missing");
  insistOne(snapshot.value.units.length>0&&snapshot.value.units.every(u=>u.underConstruction===false&&u.buildProgress===1),"native baseline contains unfinished units");
  const result=raw.filter(r=>BigInt(r.sequence)>BigInt(snapshot.sequence));result.unshift({...snapshot,kind:"baseline"});
  const stockStat=lstatSync(h.paths.stockTrace);insistOne(stockStat.isFile()&&!stockStat.isSymbolicLink()&&stockStat.nlink===1&&stockStat.size<=16*1024*1024,"stock reader physical bound changed");let stockText=readFileSync(h.paths.stockTrace,"utf8");stockText=stockText.slice(0,stockText.lastIndexOf("\n")+1);const stock=parseStockTraceJsonl(stockText);
  for(const r of stock){if(r.reader.status!=="complete")continue;insistOne(r.runId===h.runId&&sameRef(r.context.actor,h.actors.factory)&&r.nativeBasis.processIncarnation===h.attribution.processIncarnation&&r.nativeBasis.stateChannelIncarnation===h.attribution.stateChannelIncarnation,"stock queue origin/basis changed");
    const o=observations(rows).find(o=>o.basis.stateSequence===r.nativeBasis.stateSequence&&o.basis.processIncarnation===r.nativeBasis.processIncarnation&&o.basis.stateChannelIncarnation===r.nativeBasis.stateChannelIncarnation&&o.basis.matchId===r.nativeBasis.matchIncarnation&&Number(o.basis.nativeFrame)===r.nativeBasis.frame),q=queue(o,h.actors.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");
    if(r.context.domain!=="production"||q?.complete!==true||q.repeat!==false||String(q.revision)!==r.queue.revision||q.entries?.length!==r.queue.entries.length)continue;
    result.push({...snapshot,kind:r.phase==="final-read"?"final-read":"queue-observation",sequence:r.sequence,stateSequence:r.nativeBasis.stateSequence,nativeFrame:r.readFrame,value:{actor:r.context.actor,nativeBasis:r.nativeBasis,catalogueId:r.context.catalogueId,catalogueRevision:r.context.catalogueRevision,queueRevision:r.queue.revision,complete:true,repeat:false,entries:r.queue.entries.map(e=>({definitionId:-e.id,codedOptions:e.codedOptions,tag:e.tag,float32params:e.float32params})),dispatch:r.dispatch}});
  }return result;
}
export function assertOneProducedUnit(rows,before,native,h){
  const submits=rows.filter(r=>r.kind==="submit").map(r=>r.value);insistOne(submits.length===1,"exactly one submission required, no retry");const s=submits[0],f=h.actors.factory;
  insistOne(s.intent?.action==="factoryProduce"&&s.intent.actors?.length===1&&sameRef(s.intent.actors[0],f)&&s.intent.factoryProduce?.count===1&&s.intent.factoryProduce.queuePolicy==="TACTICAL_QUEUE_POLICY_APPEND"&&Number(s.intent.factoryProduce.definitionId)===h.setup.productDefinitionId,"one actor Append Count1 definition changed");
  insistOne(plannedChildCount(s.intent)===1&&s.parentId&&s.inputId&&s.module?.sha256&&s.controller&&s.basis,"parent/input/module/controller/basis missing");insistOne(Buffer.from(s.module.sha256,"base64").toString("hex")===h.artifacts.guest.sha256,"submitted module differs from actual produced guest");
  const result=rows.filter(r=>r.kind==="result").map(r=>r.value);insistOne(result.every(r=>r.parentId===s.parentId&&r.childCount===1&&(r.childIndex??0)===0&&sameRef(r.actor,f)&&r.inputId===s.inputId&&JSON.stringify(r.module)===JSON.stringify(s.module)&&JSON.stringify(r.controller)===JSON.stringify(s.controller)&&JSON.stringify(r.basis)===JSON.stringify(s.basis)),"foreign parent/input/module/controller/basis/child lifecycle");
  for(const [stage,status]of[["LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"],["LIVE_RESULT_STAGE_NATIVE_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"],["LIVE_RESULT_STAGE_NATIVE_DISPATCH","LIVE_RESULT_STATUS_APPLIED"]])insistOne(result.filter(r=>r.stage===stage&&r.status===status).length===1,`unique ${stage} result missing`);
  insistOne(result.length===3,"extra lifecycle result");const dispatch=result.find(r=>r.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH");insistOne(Number.isInteger(dispatch.nativeFrame),"actual dispatch frame missing");
  insistOne(before.basis.processIncarnation===h.attribution.processIncarnation&&before.basis.stateChannelIncarnation===h.attribution.stateChannelIncarnation&&before.basis.matchId===s.basis.matchId,"baseline/session incarnation changed");
  const baseline=native[0];insistOne(baseline?.kind==="baseline"&&baseline.stateSequence===before.basis.stateSequence,"frozen native baseline missing");
  const initial=queue(before,f,"QUEUE_DOMAIN_FACTORY_PRODUCTION");insistOne(initial?.complete&&initial.repeat===false&&initial.entries?.length===0,"empty complete repeat-off baseline missing");
  const observed=observations(rows).filter(o=>BigInt(o.basis.stateSequence)>BigInt(s.basis.stateSequence)&&Number(o.basis.nativeFrame)>dispatch.nativeFrame&&o.basis.processIncarnation===s.basis.processIncarnation&&o.basis.stateChannelIncarnation===s.basis.stateChannelIncarnation&&o.basis.matchId===s.basis.matchId);
  const known=new Set(before.units.map(u=>key(u.reference))),created=native.filter(r=>r.kind==="unit-created"&&r.nativeFrame>=dispatch.nativeFrame&&BigInt(r.stateSequence)>BigInt(s.basis.stateSequence)),finished=native.filter(r=>r.kind==="unit-finished"&&r.nativeFrame>=dispatch.nativeFrame&&BigInt(r.stateSequence)>BigInt(s.basis.stateSequence));
  insistOne(created.every(r=>r.disposition==="invalidated")&&finished.every(r=>r.disposition==="invalidated"),"unit lifecycle delta did not retain unsupported-event invalidation");
  const nativeDispatch=native.filter(r=>r.kind==="command-dispatch");insistOne(nativeDispatch.length===1&&String(nativeDispatch[0].value.batchSequence)===String(dispatch.batchSequence)&&String(nativeDispatch[0].value.correlationId)===String(dispatch.correlationId)&&String(nativeDispatch[0].value.unitId)===f.id&&nativeDispatch[0].value.commandChannelIncarnation===dispatch.commandChannelIncarnation&&nativeDispatch[0].value.status==="CommandDispatchApplied"&&nativeDispatch[0].value.dispatchFrame===dispatch.nativeFrame,"unique genuine dispatch event missing or extra native dispatch");
  insistOne(created.length===1&&finished.length===1&&String(created[0].value.builderId)===f.id&&String(created[0].value.unitId)===String(finished[0].value.unitId)&&BigInt(finished[0].sequence)>BigInt(created[0].sequence)&&finished[0].nativeFrame>=created[0].nativeFrame,"unique genuine builder creation and finished events missing");
  const queued=native.filter(r=>r.kind==="queue-observation"&&r.nativeFrame>=dispatch.nativeFrame&&sameRef(r.value.actor,f)&&r.value.complete===true&&r.value.repeat===false&&r.value.entries?.length===1&&Number(r.value.entries[0].definitionId)===h.setup.productDefinitionId&&r.value.entries[0].codedOptions===0&&r.value.entries[0].float32params?.length===0);
  insistOne(queued.length>0,"exact native queue entry with options 0 missing");
  const later=observed.filter(o=>Number(o.basis.nativeFrame)>finished[0].nativeFrame&&queue(o,f,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.complete===true&&queue(o,f,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.repeat===false&&queue(o,f,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.entries?.length===0);
  insistOne(later.length>=2&&BigInt(later.at(-1).basis.stateSequence)>BigInt(later.at(-2).basis.stateSequence),"two later empty repeat-off snapshots missing");
  for(const o of later){insistOne(native.some(r=>r.kind==="snapshot"&&r.disposition==="materialized"&&r.stateSequence===o.basis.stateSequence&&r.nativeFrame===Number(o.basis.nativeFrame)&&BigInt(r.sequence)>BigInt(finished[0].sequence)),"later browser state lacks complete native replacement after invalidation");const fresh=o.units.filter(u=>!known.has(key(u.reference)));insistOne(fresh.length===1&&String(fresh[0].reference.id)===String(created[0].value.unitId)&&Number(unit(o,fresh[0].reference)?.definitionId)===h.setup.productDefinitionId,"exactly one new product lifetime missing or extra production");}
  const final=native.filter(r=>r.kind==="final-read"&&r.nativeFrame<=dispatch.nativeFrame&&sameRef(r.value.actor,f)&&r.value.complete===true&&r.value.repeat===false&&r.value.entries?.length===0);
  insistOne(final.length===1,"one genuine predispatch final native fence missing");const d=final[0].value.dispatch;insistOne(d?.matched===true&&String(d.batchSequence)===String(dispatch.batchSequence)&&String(d.correlationId)===String(dispatch.correlationId)&&d.moduleSha256===h.artifacts.guest.sha256&&String(d.moduleGeneration)===String(s.module.generation)&&d.brokerSessionId===s.controller.sessionId&&d.commandChannelIncarnation===dispatch.commandChannelIncarnation&&d.commandIndex===nativeDispatch[0].value.commandIndex&&String(d.expectedQueueRevision)===String(s.intent.actorTacticalBindings?.find(b=>sameRef(b.actor,f))?.queueRevisions?.find(q=>q.domain==="QUEUE_DOMAIN_FACTORY_PRODUCTION")?.revision)&&final[0].value.nativeBasis.stateSequence===s.basis.stateSequence&&final[0].value.nativeBasis.token===s.basis.token&&final[0].value.nativeBasis.matchIncarnation===s.basis.matchId&&final[0].value.catalogueId===s.intent.factoryProduce.catalogueId&&String(final[0].value.catalogueRevision)===String(s.intent.factoryProduce.catalogueRevision)&&String(d.authorityEpoch)===String(s.controller.authorityEpoch),"final native dispatch/module/authority/catalogue/queue-basis join missing");
  const terminal=native.filter(r=>r.kind==="queue-observation"&&r.nativeFrame>=Number(later.at(-1).basis.nativeFrame)&&sameRef(r.value.actor,f)&&r.value.complete===true&&r.value.repeat===false&&r.value.entries?.length===0);insistOne(terminal.length>0,"later terminal native queue read missing");return{schema:"fsbar.barc-one-produced-unit-evidence/v1",runId:h.runId,parentId:s.parentId,product:later.at(-1).units.find(u=>!known.has(key(u.reference))).reference,builder:f,createdSequence:created[0].sequence,finishedSequence:finished[0].sequence,finalReadSequence:final[0].sequence,terminalReadSequence:terminal.at(-1).sequence,unitProduced:true,fullSix:false,nativeUsefulPlay:"0/6"};
}
test.describe(oneUnitCase,()=>{
  test.skip(!oneUnitEnabled,"requires root-admitted checked one-unit capsule and genuine native attribution feed");
  test("one Append Count1 completes exactly one factory-attributed unit",async({page})=>{
    test.setTimeout(180000);const h=oneUnitHandoff,j={receiverUrl:h.connection.receiverUrl,gatewayUrl:h.connection.gatewayUrl,allowedOrigin:h.connection.allowedOrigin,expectedSessionId:h.connection.sessionId,credential:h.connection.credential,bundledGuestSha256:h.artifacts.guest.sha256,outputPath:h.paths.capture,armFailurePath:`${h.paths.capture}.arm-failure.json`,deferArm:true},journal=captureJournal(h.paths.capture,h.paths.release,h.runId,h.source,oneUnitCase);
    try{const rows=await capture(page,journal),live=await pair(page,j,"Manual guest",rows),f=h.actors.factory;await select(page,live,"pointer",[f]);
      const seeded=queue(latest(rows),f,"QUEUE_DOMAIN_FACTORY_PRODUCTION");insistOne(seeded?.complete===true&&seeded.repeat===false&&seeded.entries?.length>0&&Number(seeded.entries[0].definitionId)===h.setup.seedDefinitionId,"nonempty distinct seed readiness missing");
      await expect.poll(()=>{const q=queue(latest(rows),f,"QUEUE_DOMAIN_FACTORY_PRODUCTION");return q?.complete===true&&q.repeat===false&&q.entries?.length===0},{timeout:60000}).toBe(true);
      const before=structuredClone(latest(rows));insistOne(rows.filter(r=>r.kind==="submit").length===0,"autonomous/baseline submit");
      nativeOneEvents(h,rows,before); // The pinned actual source qualification must separately prove autonomous decisions disabled.
      journal.append("one-unit-baseline",before);rows.readiness.phase="arm-clicked";await live.getByRole("button",{name:"Arm live"}).click();await expect.poll(()=>rows.readiness.armSha256).toBe(rows.readiness.moduleSha256);await expect(live.locator(".authority")).toContainText("arm native confirmed");insistOne(rows.readiness.armCount===1,"exactly one Arm required");
      await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Definition").selectOption(String(h.setup.productDefinitionId));await live.getByLabel("Count").fill("1");await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_APPEND");await physicalSubmit(page,live,"pointer");await expect.poll(()=>rows.filter(r=>r.kind==="submit").length,{timeout:5000}).toBe(1);const submit=rows.find(r=>r.kind==="submit").value;await settleSubmit(rows,submit,"applied");
      // No stale-basis replacement: this route submits once or refuses.
      let proof;await expect.poll(()=>{try{proof=assertOneProducedUnit(rows,before,nativeOneEvents(h,rows,before),h);return true}catch{return false}},{timeout:90000,intervals:[25,50,100,250]}).toBe(true);journal.append("one-unit-proof",proof);journal.complete();await journal.hold();
    }finally{journal.close()}
  });
});
// ONE_UNIT_SOURCE_END
