import { expect, test } from "@playwright/test";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";
import { assertCanonicalLifecycle, assertObservedEffects, isExactStaleBasisRefusal, isFreshPhysicalReplacement, loadStockSmokeHandoff, loadTacticalHandoff, plannedChildCount, sanitizedLifecycle, waitForTerminalOrClose } from "./tactical-native-evidence.mjs";
import { joinStockFinalRead, normalizeStockSample, parseClosedJson, parseStockTraceJsonl } from "./stock-native-trace.mjs";

const enabled=process.env.BARC_RUN_TACTICAL_NATIVE==="1",stockEnabled=process.env.BARC_RUN_STOCK_NATIVE_SMOKE==="1";if(enabled&&stockEnabled)throw new Error("full-six and selected stock smoke routes are mutually exclusive");
const handoff=enabled?await loadTacticalHandoff(process.env.BARC_TACTICAL_HANDOFF):null,stockHandoff=stockEnabled?await loadStockSmokeHandoff(process.env.BARC_STOCK_SMOKE_HANDOFF):null;
let stage,codec;
test.beforeAll(async()=>{if(!enabled&&!stockEnabled)return;stage=await mkdtemp(resolve(import.meta.dirname,"node_modules/.barc-tactical-codec-"));await cp(enabled?handoff.codecDirectory:stockHandoff.paths.codecDirectory,stage,{recursive:true});codec=await import(pathToFileURL(resolve(stage,"codec.js")).href)});
test.afterAll(async()=>{if(stage)await rm(stage,{recursive:true,force:true})});

const key=ref=>`${ref.id}:${ref.lifetime}`, sameRef=(a,b)=>String(a?.id??0)===b.id&&String(a?.lifetime??0)===b.lifetime;
const selector=(kind,ref)=>kind==="feature"?`[data-feature-id="${ref.id}"]`:`[data-unit-id="${ref.id}"][data-lifetime="${ref.lifetime}"]`;
const observations=rows=>rows.filter(x=>x.kind==="observation").map(x=>x.value), latest=rows=>observations(rows).at(-1);
const unit=(o,ref)=>o?.units?.some(x=>sameRef(x.reference,ref))&&o.preview.units.find(x=>String(x.id??0)===ref.id);
const feature=(o,ref)=>o?.tactical?.features?.find(x=>sameRef(x.reference,ref));
const actor=(o,ref)=>o?.tactical?.actors?.find(x=>sameRef(x.actor,ref));
const queue=(o,ref,domain)=>actor(o,ref)?.queue?.find(x=>x.domain===domain);
const near=(a,b,t=64)=>a&&Math.hypot(a.x-b.x,a.z-b.z)<=t;

async function capture(page){const rows=[],connection={closed:false,error:false};Object.defineProperty(rows,"connection",{value:connection});page.on("websocket",socket=>{socket.on("framesent",event=>{try{const e=codec.canonicalObject(codec.v1.LiveClientEnvelope,Uint8Array.from(event.payload));if(e.body==="submit")rows.push({direction:"client",kind:"submit",value:e.submit})}catch{}});socket.on("framereceived",event=>{try{const e=codec.canonicalObject(codec.v1.LiveServerEnvelope,Uint8Array.from(event.payload));if(["result","observation","controllerState"].includes(e.body))rows.push({direction:"server",kind:e.body,value:e[e.body]})}catch{}});socket.on("close",()=>{connection.closed=true});socket.on("socketerror",()=>{connection.error=true})});return rows}
async function pair(page,j,guest="Manual guest"){
  await page.goto(j.receiverUrl);const live=page.locator(".barc-preview.barc-live");await live.getByLabel("Gateway").fill(j.gatewayUrl);await live.getByLabel("Session UUID").fill(j.expectedSessionId);await live.getByLabel("One-time credential").fill(j.credential);await live.getByRole("button",{name:"Pair"}).click();
  await expect(live.locator(".catalogue")).not.toContainText("unavailable");await expect(live.locator(".economy")).toContainText("Economy");
  if(guest==="Imported guest"){const hash=createHash("sha256").update(await readFile(j.guestPath)).digest("hex");expect(hash).toBe(j.guestSha256);await live.getByRole("button",{name:"Import .wasm"}).click();await live.locator("[data-file]").setInputFiles(j.guestPath)}else await live.getByRole("button",{name:guest}).click();
  await live.getByRole("button",{name:"Arm live"}).click();await expect(live.locator(".authority")).toContainText("arm native confirmed");return live;
}
async function target(live,p){await live.getByLabel("Target X").fill(String(p.x));await live.getByLabel("Target Z").fill(String(p.z))}
async function keyboardSelect(page,live,refs){const map=live.getByLabel(/Live tactical map/);await map.focus();for(let i=0;i<64&&!((await live.locator(".selection").textContent())??"").includes(key(refs[0]));i++)await page.keyboard.press("Tab");expect(await live.locator(".selection").textContent()).toContain(key(refs[0]));for(const ref of refs.slice(1)){for(let i=0;i<64&&!((await live.locator(".selection").textContent())??"").includes(key(ref));i++)await page.keyboard.press("Control+Tab");expect(await live.locator(".selection").textContent()).toContain(key(ref))}}
const selectedRefs=async live=>{const value=(await live.locator(".selection").textContent())??"",match=/^Actors (.*?) ·/.exec(value);return match?match[1].split(", "):[]}
async function actorPoint(live,ref){
  const actor=live.locator(selector("unit",ref));let point=null;
  await expect.poll(async()=>{
    point=await actor.evaluate((node,expected)=>{
      if(!node.isConnected||node.dataset.unitId!==expected.id||node.dataset.lifetime!==expected.lifetime)return null;
      node.scrollIntoView({block:"center",inline:"center"});
      const box=node.getBoundingClientRect(),x=box.left+box.width/2,y=box.top+box.height/2;
      return box.width>0&&box.height>0&&Number.isFinite(x)&&Number.isFinite(y)&&x>=0&&y>=0&&x<innerWidth&&y<innerHeight?{x,y}:null;
    },ref).catch(()=>null);
    return point;
  },{timeout:30000,intervals:[0,10,25,50,100,250]}).not.toBeNull();
  return point;
}
async function pointerSelect(page,live,ref,expected,toggle=false){for(let attempt=0;attempt<64;attempt++){const point=await actorPoint(live,ref);if(toggle)await page.keyboard.down("Control");try{await page.mouse.click(point.x,point.y)}finally{if(toggle)await page.keyboard.up("Control")}if(JSON.stringify(await selectedRefs(live))===JSON.stringify(expected.map(key)))return}throw new Error(`pointer could not establish exact actor set ${expected.map(key).join(", ")}`)}
async function select(page,live,source,refs){if(source==="keyboard")return keyboardSelect(page,live,refs);for(let i=0;i<refs.length;i++)await pointerSelect(page,live,refs[i],refs.slice(0,i+1),i>0)}
async function cycleTarget(page,live,kind,ref){const map=live.getByLabel(/Live tactical map/),letter=kind==="friendly"?"t":"f",label=kind==="friendly"?"Friendly":"Feature";await map.focus();for(let i=0;i<64&&!((await live.locator(".target").textContent())??"").includes(`${label} ${key(ref)}`);i++)await page.keyboard.press(letter);expect(await live.locator(".target").textContent()).toContain(`${label} ${key(ref)}`)}
async function setFriendly(page,live,source,ref){if(source==="keyboard")return cycleTarget(page,live,"friendly",ref);const before=await selectedRefs(live);for(let attempt=0;attempt<64;attempt++){const point=await actorPoint(live,ref);await page.keyboard.down("Shift");try{await page.mouse.click(point.x,point.y)}finally{await page.keyboard.up("Shift")}expect(await selectedRefs(live)).toEqual(before);if(((await live.locator(".target").textContent())??"").includes(`Friendly ${key(ref)}`))return}throw new Error(`pointer could not reach friendly actor ${key(ref)} through overlapping map targets`)}
async function setFeature(page,live,source,ref){if(source==="keyboard")await cycleTarget(page,live,"feature",ref);else await live.locator(selector("feature",ref)).click()}

const terminal=value=>value.status==="LIVE_RESULT_STATUS_REJECTED"||value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"||value.stage==="LIVE_RESULT_STAGE_UNKNOWN";
async function settleSubmit(rows,submit,expectation="applied"){
  const count=plannedChildCount(submit.intent);await waitForTerminalOrClose(rows,rows.connection,submit.parentId,count);
  const values=rows.filter(x=>x.kind==="result"&&x.value.parentId===submit.parentId),applied=values.filter(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_APPLIED");
  if(expectation==="applied")expect(applied).toHaveLength(count);else if(expectation==="broker-refused"){expect(applied).toHaveLength(0);expect(values).toHaveLength(count);expect(values.every(x=>x.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_REJECTED"&&x.value.disposition==="LIVE_RESULT_DISPOSITION_RECORDED"&&JSON.stringify(x.value.basis)===JSON.stringify(submit.basis))).toBeTruthy()}else if(expectation==="native-refused"){expect(applied).toHaveLength(0);expect(values.filter(x=>x.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_ACCEPTED")).toHaveLength(count);expect(values.some(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_REJECTED"||x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_SKIPPED")).toBeTruthy()}else{expect(applied.length).toBeGreaterThan(0);expect(applied.length).toBeLessThan(count);expect(values.filter(x=>x.value.stage==="LIVE_RESULT_STAGE_BROKER_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_ACCEPTED")).toHaveLength(count)}return submit;
}
async function waitEffect(rows,action,predicate){await expect.poll(()=>observations(rows).slice(action.observationCount).find(o=>predicate(action.beforeObservation,o))?.basis?.stateSequence??null,{timeout:120000}).not.toBeNull();const hit=observations(rows).slice(action.observationCount).find(o=>predicate(action.beforeObservation,o));action.effectObservationSequence=hit.basis.stateSequence;return hit}
async function physicalSubmit(page,live,source){if(source==="pointer")await live.getByRole("button",{name:"Send tactical command"}).click();else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("Enter")}}
async function trigger(page,live,rows,source,family,{expectation="applied",effect}={}){
  const before=rows.filter(x=>x.kind==="submit").length,action={kind:"action",family,source,beforeObservation:latest(rows),observationCount:observations(rows).length};rows.push(action);await physicalSubmit(page,live,source);await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+1);let submit=rows.filter(x=>x.kind==="submit")[before].value;
  const count=plannedChildCount(submit.intent);await waitForTerminalOrClose(rows,rows.connection,submit.parentId,count);
  if(expectation==="applied"&&isExactStaleBasisRefusal(rows,submit)){
    const staleSequence=BigInt(submit.basis.stateSequence);action.submitCount=2;action.causalSubmitOrdinal=1;action.staleBasisRefresh={rejectedStateSequence:submit.basis.stateSequence,originalBeforeObservation:action.beforeObservation,originalObservationCount:action.observationCount};
    await expect(live.locator(".result")).toContainText("LIVE_RESULT_STAGE_BROKER_ADMISSION: LIVE_RESULT_STATUS_REJECTED");
    await expect.poll(()=>BigInt(latest(rows)?.basis?.stateSequence??0)>staleSequence,{timeout:30000}).toBe(true);
    action.beforeObservation=latest(rows);action.observationCount=observations(rows).length;
    await physicalSubmit(page,live,source);await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+2);submit=rows.filter(x=>x.kind==="submit")[before+1].value;
    expect(isFreshPhysicalReplacement(rows.filter(x=>x.kind==="submit")[before].value,submit,observations(rows))).toBeTruthy();action.staleBasisRefresh.freshStateSequence=submit.basis.stateSequence;
  }
  await settleSubmit(rows,submit,expectation);if(effect)await waitEffect(rows,action,effect);return{submit,action};
}

async function exerciseManual(page,j,rows,source){
  const live=await pair(page,j),descriptor=(ref,kind)=>actor(latest(rows),ref)?.descriptors?.some(x=>x.kind===kind&&!x.disabled);
  const reclaimed=(before,o,predicate)=>{const a=before.tactical?.economy?.metal,b=o.tactical?.economy?.metal;if(!predicate(o)||!Number.isFinite(a?.current)||!Number.isFinite(b?.current))return false;const seconds=Math.max(0,(Number(o.preview.capturedAtUnixMs)-Number(before.preview.capturedAtUnixMs))/1000);return b.current-a.current>(a.incomePerSecond??0)*seconds+(j.resourceAttributionTolerance??0.01)};
  await select(page,live,source,[j.builder]);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await live.getByLabel("Facing").selectOption("BUILD_FACING_SOUTH");const beforeBuild=new Set(latest(rows).units.map(x=>key(x.reference)));await trigger(page,live,rows,source,"construction",{effect:(_,o)=>o.units.some(x=>!beforeBuild.has(key(x.reference))&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)})?.definitionId===j.buildDefinitionId&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).health>=unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).maxHealth)});rows.push({kind:"action",family:"economy",source,noSubmit:true,beforeObservation:latest(rows)});
  for(const[family,actionKind,targetRef,keyName]of[["guard","guard",j.repairTarget,"g"],["repair","repair",j.repairTarget,"r"],["reclaimUnit","reclaimUnit",j.reclaimUnitTarget,"l"]]){await select(page,live,source,[j.builder]);await setFriendly(page,live,source,targetRef);if(source==="keyboard"){await live.getByLabel(/Live tactical map/).focus();await page.keyboard.press(keyName)}else await live.getByLabel("Action").selectOption(actionKind);const before=latest(rows),health=unit(before,targetRef)?.health;await trigger(page,live,rows,source,family,{effect:(_,o)=>family==="guard"?queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>e.action==="LIVE_ACTION_KIND_GUARD"&&sameRef(e.unitTarget,targetRef)):family==="repair"?unit(o,targetRef)?.health>health:reclaimed(before,o,x=>!unit(x,targetRef)||unit(x,targetRef).health<health)})}
  await select(page,live,source,[j.builder]);await setFeature(page,live,source,j.feature);if(source==="keyboard"){await live.getByLabel(/Live tactical map/).focus();await page.keyboard.press("x")}const featureStart=latest(rows),featureBefore=feature(featureStart,j.feature)?.reclaimLeft;await trigger(page,live,rows,source,"reclaimFeature",{effect:(_,o)=>reclaimed(featureStart,o,x=>!feature(x,j.feature)||feature(x,j.feature).reclaimLeft<featureBefore)});
  await select(page,live,source,[j.builder]);await target(live,j.positions.reclaim);await live.getByLabel("Action").selectOption("reclaimArea");const areaStart=latest(rows),areaBefore=feature(areaStart,j.areaFeature)?.reclaimLeft;await trigger(page,live,rows,source,"reclaimArea",{effect:(_,o)=>reclaimed(areaStart,o,x=>!feature(x,j.areaFeature)||feature(x,j.areaFeature).reclaimLeft<areaBefore)});

  await select(page,live,source,[j.factory]);await target(live,j.positions.rally);await live.getByLabel("Action").selectOption("setRally");const rallyRev=queue(latest(rows),j.factory,"QUEUE_DOMAIN_FACTORY_RALLY")?.revision;await trigger(page,live,rows,source,"rally",{effect:(_,o)=>queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_RALLY")?.revision!==rallyRev});
  await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Definition").selectOption(String(j.existingProductionDefinitionId));await live.getByLabel("Count").fill("1");await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_APPEND");await trigger(page,live,rows,source,"factoryAppendSeed",{effect:(_,o)=>{const value=queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");return value?.complete&&value.repeat===false&&value.entries?.length>0&&Number(value.entries[0].definitionId)===j.existingProductionDefinitionId}});
  await live.getByLabel("Definition").selectOption(String(j.productDefinitionId));await live.getByLabel("Count").fill(String(j.productionCount));const beforeProducts=new Set(latest(rows).units.map(x=>key(x.reference)));const factory=await trigger(page,live,rows,source,"factoryAppendQuantity",{effect:(_,o)=>{const made=o.units.filter(x=>!beforeProducts.has(key(x.reference))&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)})?.definitionId===j.productDefinitionId);return made.length===Number(j.productionCount)&&made.every(x=>near(unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).position,j.positions.rally,j.rallyTolerance??64))}});expect(plannedChildCount(factory.submit.intent)).toBe(Number(j.productionCount));
  await live.getByLabel("Definition").selectOption(String(j.existingProductionDefinitionId));await live.getByLabel("Count").fill("1");await trigger(page,live,rows,source,"factoryReplaceSeed",{effect:(_,o)=>{const value=queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");return value?.complete&&value.repeat===false&&value.entries?.length>0&&Number(value.entries[0].definitionId)===j.existingProductionDefinitionId}});await live.getByLabel("Definition").selectOption(String(j.productDefinitionId));await live.getByLabel("Count").fill(String(j.productionCount));await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REPLACE");const replaceBefore=latest(rows),replaceQueue=structuredClone(queue(replaceBefore,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")),replaceRally=structuredClone(queue(replaceBefore,j.factory,"QUEUE_DOMAIN_FACTORY_RALLY")),replace=await trigger(page,live,rows,source,"factoryReplaceNonemptySafety",{expectation:"broker-refused"});await expect.poll(()=>{const value=latest(rows);return BigInt(value?.basis?.stateSequence??0)>BigInt(replace.submit.basis.stateSequence)&&JSON.stringify(queue(value,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION"))===JSON.stringify(replaceQueue)&&JSON.stringify(queue(value,j.factory,"QUEUE_DOMAIN_FACTORY_RALLY"))===JSON.stringify(replaceRally)},{timeout:30000}).toBe(true);replace.action.safetyObservationSequence=latest(rows).basis.stateSequence;await expect.poll(()=>queue(latest(rows),j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.entries?.length??-1,{timeout:120000}).toBe(0);
  await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_FACTORY_PRODUCTION");await live.getByLabel("Action").selectOption("queueEdit");expect(queue(latest(rows),j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.entries).toHaveLength(0);await live.getByLabel("Queue operation").selectOption("repeat-on");await trigger(page,live,rows,source,"queueRepeat",{effect:(_,o)=>queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.repeat===true});await live.getByLabel("Queue operation").selectOption("repeat-off");await trigger(page,live,rows,source,"queueRepeatOff",{effect:(_,o)=>queue(o,j.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION")?.repeat===false});

  await select(page,live,source,[j.builder]);await live.getByLabel("Action").selectOption("queueEdit");await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_ACTOR_ORDER");await live.getByLabel("Queue operation").selectOption("insert");const insertRev=queue(latest(rows),j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.revision;const inserted=await trigger(page,live,rows,source,"queueInsert",{effect:(_,o)=>queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.revision!==insertRev&&queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.length>0});const tag=queue(latest(rows),j.builder,"QUEUE_DOMAIN_ACTOR_ORDER").entries[0].nativeTag;expect(Number(tag)).toBeGreaterThan(0);inserted.action.observedNativeTag=String(tag);
  await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REJECT_IF_BUSY");await trigger(page,live,rows,source,"rejectBusy",{expectation:"native-refused"});await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REPLACE");
  await live.getByLabel("Action").selectOption("queueEdit");await live.getByLabel("Queue operation").selectOption("remove");const removed=await trigger(page,live,rows,source,"queueRemove",{effect:(_,o)=>!queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>String(e.nativeTag)===String(tag))});removed.action.observedNativeTag=String(tag);
  await live.getByLabel("Queue operation").selectOption("insert");await trigger(page,live,rows,source,"queueInsertForStale",{effect:(_,o)=>queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.length>0});await live.getByLabel("Queue operation").selectOption("remove");const staleTag=String(queue(latest(rows),j.builder,"QUEUE_DOMAIN_ACTOR_ORDER").entries[0].nativeTag),staleBefore=rows.filter(x=>x.kind==="submit").length,stale={kind:"action",family:"staleRevision",source,submitCount:2,beforeObservation:latest(rows),observationCount:observations(rows).length,observedNativeTag:staleTag};rows.push(stale);const control=source==="pointer"?live.getByRole("button",{name:"Send tactical command"}):live.getByLabel(/Live tactical map/);await control.evaluate((node,keyboard)=>{if(keyboard){node.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}));node.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}))}else{node.click();node.click()}},source==="keyboard");await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(staleBefore+2);const staleSubmits=rows.filter(x=>x.kind==="submit").slice(staleBefore,staleBefore+2).map(x=>x.value);expect(staleSubmits[0].basis).toEqual(staleSubmits[1].basis);expect(staleSubmits[0].intent.actorTacticalBindings).toEqual(staleSubmits[1].intent.actorTacticalBindings);await settleSubmit(rows,staleSubmits[0],"applied");await settleSubmit(rows,staleSubmits[1],"native-refused");await waitEffect(rows,stale,(_,o)=>!queue(o,j.builder,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>String(e.nativeTag)===staleTag));

  for(const[family,kind,ref]of[["barConstructionPriority","TACTICAL_DESCRIPTOR_BAR_CONSTRUCTION_PRIORITY",j.modeActors.constructionPriority],["barCloakDesire","TACTICAL_DESCRIPTOR_BAR_CLOAK_DESIRE",j.modeActors.cloakDesire]]){expect(descriptor(ref,kind)).toBeTruthy();await select(page,live,source,[ref]);await live.getByLabel("Action").selectOption("tacticalMode");await live.getByLabel("Mode").selectOption(kind);await live.getByLabel("Mode value").selectOption("TACTICAL_MODE_VALUE_ENABLED");await trigger(page,live,rows,source,family,{effect:(_,o)=>actor(o,ref)?.descriptors?.some(d=>d.kind===kind&&d.observedModeValue==="TACTICAL_MODE_VALUE_ENABLED")})}
  await select(page,live,source,j.mixedActors);await setFriendly(page,live,source,j.repairTarget);await live.getByLabel("Action").selectOption(j.mixedAction);const mixed=await trigger(page,live,rows,source,"mixedChildren",{expectation:"mixed",effect:(_,o)=>queue(o,j.mixedAppliedActor,"QUEUE_DOMAIN_ACTOR_ORDER")?.entries?.some(e=>e.action==="LIVE_ACTION_KIND_GUARD"&&sameRef(e.unitTarget,j.repairTarget))});expect(mixed.submit.intent.actors.map(x=>key({id:String(x.id??0),lifetime:String(x.lifetime)}))).toEqual(j.mixedActors.map(key));const mixedRows=rows.filter(x=>x.kind==="result"&&x.value.parentId===mixed.submit.parentId),forActor=ref=>mixedRows.filter(x=>sameRef(x.value.actor,ref));expect(forActor(j.mixedAppliedActor).some(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_APPLIED")).toBeTruthy();expect(forActor(j.mixedRefusedActor).some(x=>x.value.stage==="LIVE_RESULT_STAGE_NATIVE_ADMISSION"&&x.value.status==="LIVE_RESULT_STATUS_REJECTED"||x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_SKIPPED")).toBeTruthy();
  await select(page,live,source,[j.builder]);const health=unit(latest(rows),j.combatTarget)?.health,before=rows.filter(x=>x.kind==="submit").length,action={kind:"action",family:"combat",source,beforeObservation:latest(rows),observationCount:observations(rows).length};rows.push(action);if(source==="pointer")await live.locator(selector("unit",j.combatTarget)).click();else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("a");await page.keyboard.press("Enter")}await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+1);await settleSubmit(rows,rows.filter(x=>x.kind==="submit")[before].value,"applied");await waitEffect(rows,action,(_,o)=>unit(o,j.combatTarget)?.health<health);
}

async function imported(page,j,rows){const live=await pair(page,j,"Imported guest");await select(page,live,"pointer",j.importedActors);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));const ids=new Set(latest(rows).units.map(x=>key(x.reference)));await trigger(page,live,rows,"pointer","importedPolicyEffect",{effect:(_,o)=>o.units.some(x=>!ids.has(key(x.reference))&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)})?.definitionId===j.buildDefinitionId&&unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).health>=unit(o,{id:String(x.reference.id??0),lifetime:String(x.reference.lifetime)}).maxHealth)});const before=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family:"zeroWriteRefusal",source:"pointer",noSubmit:true,beforeObservation:latest(rows)});await live.getByLabel("Action").selectOption(j.unavailableAction??"setRally");await live.getByRole("button",{name:"Send tactical command"}).click({force:true});await page.waitForTimeout(250);expect(rows.filter(x=>x.kind==="submit")).toHaveLength(before)}

test.describe("actual tactical BAR receiver",()=>{test.skip(!enabled,"requires parent-owned tactical native handoff");for(const product of handoff?.products??[])for(const journey of product.journeys)test(`${product.id} ${journey.mode} reaches fenced tactical effects`,async({page})=>{const rows=await capture(page);try{if(journey.mode==="pointer")await exerciseManual(page,journey,rows,"pointer");else if(journey.mode==="keyboard")await exerciseManual(page,journey,rows,"keyboard");else await imported(page,journey,rows);const planned=[];let active=null,remaining=0,ordinal=0;for(const row of rows){if(row.kind==="action"&&!row.noSubmit){active=row;remaining=row.submitCount??1;ordinal=0}else if(row.kind==="submit"){planned.push({submit:row.value,action:active,family:active?.family,ordinal:ordinal++});if(--remaining<=0)active=null}}const parents=planned.map(({submit,action,family,ordinal})=>{const refreshed=action?.causalSubmitOrdinal===1;if(refreshed&&ordinal===0)expect(isExactStaleBasisRefusal(rows,submit)).toBeTruthy();return{id:submit.parentId,childCount:plannedChildCount(submit.intent),requireApplied:refreshed?ordinal===1:!["rejectBusy","mixedChildren","factoryReplaceNonemptySafety"].includes(family)&&(family!=="staleRevision"||ordinal===0),requireNonApplied:refreshed?ordinal===0:["rejectBusy","factoryReplaceNonemptySafety"].includes(family)||(family==="staleRevision"&&ordinal===1),requireMixed:family==="mixedChildren"}}),stages={LIVE_RESULT_STAGE_BROKER_ADMISSION:"BrokerAdmission",LIVE_RESULT_STAGE_NATIVE_ADMISSION:"NativeAdmission",LIVE_RESULT_STAGE_NATIVE_DISPATCH:"NativeDispatch",LIVE_RESULT_STAGE_UNKNOWN:"Unknown"},statuses={LIVE_RESULT_STATUS_ACCEPTED:"Accepted",LIVE_RESULT_STATUS_REJECTED:"Rejected",LIVE_RESULT_STATUS_APPLIED:"Applied",LIVE_RESULT_STATUS_SKIPPED:"Skipped",LIVE_RESULT_STATUS_EXPIRED:"Expired",LIVE_RESULT_STATUS_UNKNOWN:"Unknown"},results=rows.filter(x=>x.kind==="result").map(x=>({kind:"result",parentId:x.value.parentId,childIndex:x.value.childIndex,childCount:x.value.childCount,stage:stages[x.value.stage],status:statuses[x.value.status]}));assertCanonicalLifecycle(results,parents);const coverage=assertObservedEffects(rows,journey);if(journey.mode!=="importedGuest")rows.push({kind:"coverage",value:coverage});await writeFile(journey.outputPath,rows.map(row=>JSON.stringify(row)).join("\n")+"\n",{mode:0o600,flag:"wx"})}catch(error){await writeFile(`${journey.outputPath}.partial.json`,JSON.stringify(sanitizedLifecycle(rows,rows.connection))+"\n",{mode:0o600,flag:"wx"});throw error}})});

const privateRows=async path=>(await readFile(path,"utf8")).split("\n").filter(Boolean).map(parseClosedJson);
const contentHex=value=>Buffer.from(value,"base64").toString("hex");
function hostSnapshotFor(record,hostRows){
  const row=hostRows.find(value=>value.kind==="live-metadata"&&value.tactical?.basis?.stateSequence===record.nativeBasis.stateSequence&&value.tactical?.basis?.processIncarnation===record.nativeBasis.processIncarnation&&value.tactical?.basis?.stateChannelIncarnation===record.nativeBasis.stateChannelIncarnation);expect(row,"actual matching host metadata").toBeTruthy();const actor=row.tactical.actors?.find(value=>sameRef(value.actor,record.context.actor)),page=row.catalogue?.find(value=>value.catalogueId===record.context.catalogueId&&String(value.catalogueRevision)===record.context.catalogueRevision);expect(actor,"actual host actor metadata").toBeTruthy();expect(page?.content,"actual host catalogue content").toBeTruthy();return{nativeBasis:row.tactical.basis,actor:actor.actor,catalogue:{id:page.catalogueId,revision:String(page.catalogueRevision),contentSha256:contentHex(page.content.gameContentSha256)}};
}
const wireHostResults=hostRows=>hostRows.filter(row=>row.kind==="result"&&row.wireEnvelope).map(row=>{const result=parseClosedJson(row.wireEnvelope).result;return{...row,parentId:result.parentId,actor:result.actor,basis:result.basis}});

test.describe("selected stock Count1 smoke",()=>{
  test.skip(!stockEnabled,"requires root-admitted selected stock smoke handoff");
  test("uses the production browser path and retains exact stock trace joins",async({page})=>{
    const h=stockHandoff,j={receiverUrl:h.connection.receiverUrl,gatewayUrl:h.connection.gatewayUrl,allowedOrigin:h.connection.allowedOrigin,expectedSessionId:h.connection.sessionId,credential:h.connection.credential},rows=await capture(page),live=await pair(page,j);
    await expect.poll(()=>latest(rows)?.basis?.stateSequence??null,{timeout:30000}).not.toBeNull();await select(page,live,"pointer",[h.actors.factory]);const initial=queue(latest(rows),h.actors.factory,"QUEUE_DOMAIN_FACTORY_PRODUCTION");expect(initial?.complete).toBe(true);expect(initial?.evidenceScheme).toBe("NATIVE_QUEUE_EVIDENCE_SCHEME_STOCK_LUA_SUPPORTED_FIELDS_V1");expect(initial?.entries?.length).toBeGreaterThan(0);
    await target(live,h.setup.positions.rally);await live.getByLabel("Action").selectOption("setRally");await trigger(page,live,rows,"pointer","stockSmokeRally");await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Definition").selectOption(String(h.setup.productDefinitionId));await live.getByLabel("Count").fill("1");await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_APPEND");const append=await trigger(page,live,rows,"pointer","stockSmokeAppend1");expect(plannedChildCount(append.submit.intent)).toBe(1);
    const beforeReplace=rows.filter(row=>row.kind==="submit").length;await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REPLACE");await live.getByRole("button",{name:"Send tactical command"}).click();await expect(live.locator(".result")).toContainText("No Append fallback");await page.waitForTimeout(250);expect(rows.filter(row=>row.kind==="submit")).toHaveLength(beforeReplace);
    await select(page,live,"pointer",[h.actors.builder]);await target(live,h.setup.positions.move);const beforeMove=rows.filter(row=>row.kind==="submit").length;await live.getByRole("button",{name:"Move"}).click();await expect.poll(()=>rows.filter(row=>row.kind==="submit").length,{timeout:30000}).toBe(beforeMove+1);await settleSubmit(rows,rows.filter(row=>row.kind==="submit")[beforeMove].value,"applied");const beforeAttack=rows.filter(row=>row.kind==="submit").length;await live.locator(selector("unit",h.actors.combatTarget)).click();await expect.poll(()=>rows.filter(row=>row.kind==="submit").length,{timeout:30000}).toBe(beforeAttack+1);await settleSubmit(rows,rows.filter(row=>row.kind==="submit")[beforeAttack].value,"applied");
    const trace=parseStockTraceJsonl(await readFile(h.paths.stockTrace,"utf8")),hostRows=await privateRows(h.paths.hostTrace),samples=[];for(const record of trace.filter(value=>value.phase==="sample"&&value.reader.status==="complete")){const browser=observations(rows).find(value=>value.basis?.stateSequence===record.nativeBasis.stateSequence&&value.basis?.processIncarnation===record.nativeBasis.processIncarnation&&value.basis?.stateChannelIncarnation===record.nativeBasis.stateChannelIncarnation);if(browser)samples.push(normalizeStockSample(record,hostSnapshotFor(record,hostRows),browser,codec))}expect(samples.length).toBeGreaterThan(0);
    const hostResults=wireHostResults(hostRows),browserResults=rows.filter(row=>row.kind==="result").map(row=>row.value),submits=rows.filter(row=>row.kind==="submit").map(row=>row.value),finals=trace.filter(value=>value.phase==="final-read"&&value.reader.status==="complete"),joins=[];for(const final of finals)for(const sample of samples)for(const submit of submits){try{joins.push(joinStockFinalRead(final,sample,hostResults,submit,browserResults))}catch{}}expect(joins.length).toBeGreaterThan(0);expect(joins.some(value=>value.value.parentId===append.submit.parentId&&value.value.matched)).toBe(true);
    await writeFile(h.paths.capture,rows.map(row=>JSON.stringify(row)).join("\n")+"\n",{mode:0o600,flag:"wx"});await writeFile(h.paths.output,JSON.stringify({schema:"fsbar.barc-stock-native-smoke-evidence/v1",result:"selected-smoke-observed",selection:h.selection,normalizedEvidence:samples,finalReadJoins:joins,uiReplaceRefusedWithoutSubmit:true,claims:{fullSix:false,nativeAcceptance:"0/6",publication:false,adoption:false}},null,2)+"\n",{mode:0o600,flag:"wx"});
  });
});
