import{expect,test}from"@playwright/test";import{cp,mkdtemp,rm,writeFile}from"node:fs/promises";import{pathToFileURL}from"node:url";import{resolve}from"node:path";import{assertCanonicalLifecycle,assertObservedEffects,loadTacticalHandoff,plannedChildCount}from"./tactical-native-evidence.mjs";
const enabled=process.env.BARC_RUN_TACTICAL_NATIVE==="1",handoff=enabled?await loadTacticalHandoff(process.env.BARC_TACTICAL_HANDOFF):null;
let stage,codec;
test.beforeAll(async()=>{if(!enabled)return;stage=await mkdtemp(resolve(import.meta.dirname,"node_modules/.barc-tactical-codec-"));await cp(handoff.codecDirectory,stage,{recursive:true});codec=await import(pathToFileURL(resolve(stage,"codec.js")).href)});
test.afterAll(async()=>{if(stage)await rm(stage,{recursive:true,force:true})});
const refSelector=(kind,ref)=>kind==="feature"?`[data-feature-id="${ref.id}"]`:`[data-unit-id="${ref.id}"][data-lifetime="${ref.lifetime}"]`;
async function capture(page){const rows=[];page.on("websocket",socket=>{socket.on("framesent",event=>{try{const e=codec.canonicalObject(codec.v1.LiveClientEnvelope,Uint8Array.from(event.payload));if(e.body==="submit")rows.push({direction:"client",kind:"submit",value:e.submit})}catch{}});socket.on("framereceived",event=>{try{const e=codec.canonicalObject(codec.v1.LiveServerEnvelope,Uint8Array.from(event.payload));if(["result","observation","controllerState"].includes(e.body))rows.push({direction:"server",kind:e.body,value:e[e.body]})}catch{}})});return rows}
async function pair(page,journey,guest="Manual guest"){
  await page.goto(journey.receiverUrl);const live=page.locator(".barc-preview.barc-live");await live.getByLabel("Gateway").fill(journey.gatewayUrl);await live.getByLabel("Session UUID").fill(journey.expectedSessionId);await live.getByLabel("One-time credential").fill(journey.credential);await live.getByRole("button",{name:"Pair"}).click();
  await expect(live.locator(".catalogue")).not.toContainText("unavailable");await expect(live.locator(".economy")).toContainText("Economy");
  if(guest==="Imported guest"){await live.getByRole("button",{name:"Import .wasm"}).click();await live.locator("[data-file]").setInputFiles(journey.guestPath)}else await live.getByRole("button",{name:guest}).click();
  await live.getByRole("button",{name:"Arm live"}).click();await expect(live.locator(".authority")).toContainText("arm native confirmed");return live
}
async function target(live,point){await live.getByLabel("Target X").fill(String(point.x));await live.getByLabel("Target Z").fill(String(point.z))}
async function settleSubmit(rows,submit,requireApplied=true){const parent=submit.parentId,count=plannedChildCount(submit.intent),terminal=value=>value.status==="LIVE_RESULT_STATUS_REJECTED"||value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"||value.stage==="LIVE_RESULT_STAGE_UNKNOWN";await expect.poll(()=>new Set(rows.filter(x=>x.kind==="result"&&x.value.parentId===parent&&terminal(x.value)).map(x=>x.value.childIndex)).size,{timeout:30000}).toBe(count);if(requireApplied){const applied=rows.filter(x=>x.kind==="result"&&x.value.parentId===parent&&x.value.stage==="LIVE_RESULT_STAGE_NATIVE_DISPATCH"&&x.value.status==="LIVE_RESULT_STATUS_APPLIED");expect(applied).toHaveLength(count);const frame=Math.max(...applied.map(x=>x.value.nativeFrame));await expect.poll(()=>rows.some(x=>x.kind==="observation"&&Number(x.value.basis?.nativeFrame)>frame),{timeout:120000}).toBe(true)}return submit}
async function settled(rows,before,requireApplied=true){await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(before+1);return settleSubmit(rows,rows.filter(x=>x.kind==="submit")[before].value,requireApplied)}
async function choose(live,actors){for(const[index,actor]of actors.entries())await live.locator(refSelector("unit",actor)).click(index?{modifiers:["Control"]}:{})}
async function trigger(page,live,rows,source,family,requireApplied=true){const before=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family,source,beforeObservation:rows.filter(x=>x.kind==="observation").at(-1)?.value??null});if(source==="pointer")await live.getByRole("button",{name:"Send tactical command"}).click();else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("Enter")}return settled(rows,before,requireApplied)}
async function exerciseManual(page,j,rows,source){const live=await pair(page,j),act=async(family,requireApplied=true)=>trigger(page,live,rows,source,family,requireApplied);
  await choose(live,[j.builder]);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await live.getByLabel("Facing").selectOption("BUILD_FACING_SOUTH");await act("construction");rows.push({kind:"action",family:"economy",source,observedWith:"construction/reclaim",noSubmit:true});
  for(const [family,action,targetRef]of[["guard","guard",j.repairTarget],["repair","repair",j.repairTarget],["reclaimUnit","reclaimUnit",j.reclaimUnitTarget]]){await choose(live,[j.builder]);await live.locator(refSelector("unit",targetRef)).click({modifiers:["Shift"]});await live.getByLabel("Action").selectOption(action);await act(family)}
  await choose(live,[j.builder]);await live.locator(refSelector("feature",j.feature)).click();await act("reclaimFeature");await choose(live,[j.builder]);await target(live,j.positions.reclaim);await live.getByLabel("Action").selectOption("reclaimArea");await act("reclaimArea");
  await choose(live,[j.factory]);await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Definition").selectOption(String(j.productDefinitionId));await live.getByLabel("Count").fill(String(j.productionCount??2));await act("factoryCount");await target(live,j.positions.rally);await live.getByLabel("Action").selectOption("setRally");await act("rally");
  await choose(live,[j.builder]);await live.getByLabel("Action").selectOption("queueEdit");await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_ACTOR_ORDER");for(const[family,operation]of[["queueInsert","insert"],["queueRemove","remove"]]){await live.getByLabel("Queue operation").selectOption(operation);await act(family)}await choose(live,[j.factory]);await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_FACTORY_PRODUCTION");await live.getByLabel("Queue operation").selectOption("repeat-on");await act("queueRepeat");
  await live.getByLabel("Action").selectOption("factoryProduce");await live.getByLabel("Queue policy").selectOption("TACTICAL_QUEUE_POLICY_REJECT_IF_BUSY");await act("rejectBusy",false);await choose(live,[j.builder]);await live.getByLabel("Action").selectOption("queueEdit");await live.getByLabel("Queue domain").selectOption("QUEUE_DOMAIN_ACTOR_ORDER");await live.getByLabel("Queue operation").selectOption("remove");const staleBefore=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family:"staleRevision",source,submitCount:2,beforeObservation:rows.filter(x=>x.kind==="observation").at(-1)?.value??null});if(source==="pointer"){await live.getByRole("button",{name:"Send tactical command"}).click();await live.getByRole("button",{name:"Send tactical command"}).click()}else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("Enter");await page.keyboard.press("Enter")}await expect.poll(()=>rows.filter(x=>x.kind==="submit").length,{timeout:30000}).toBe(staleBefore+2);const staleSubmits=rows.filter(x=>x.kind==="submit").slice(staleBefore,staleBefore+2).map(x=>x.value);await settleSubmit(rows,staleSubmits[0],false);await settleSubmit(rows,staleSubmits[1],false);
  await choose(live,[j.builder]);await live.getByLabel("Action").selectOption("tacticalMode");for(const[family,mode]of[["barConstructionPriority","TACTICAL_DESCRIPTOR_BAR_CONSTRUCTION_PRIORITY"],["barCloakDesire","TACTICAL_DESCRIPTOR_BAR_CLOAK_DESIRE"]]){await live.getByLabel("Mode").selectOption(mode);await live.getByLabel("Mode value").selectOption("TACTICAL_MODE_VALUE_ENABLED");await act(family)}
  await choose(live,j.mixedActors);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await act("mixedChildren",false);const combatBefore=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family:"combat",source,beforeObservation:rows.filter(x=>x.kind==="observation").at(-1)?.value??null});if(source==="pointer")await live.locator(refSelector("unit",j.combatTarget)).click();else{const map=live.getByLabel(/Live tactical map/);await map.focus();await page.keyboard.press("a");await page.keyboard.press("Enter")}await settled(rows,combatBefore)
}
async function imported(page,j,rows){const live=await pair(page,j,"Imported guest");await choose(live,j.mixedActors);await target(live,j.positions.build);await live.getByLabel("Action").selectOption("build");await live.getByLabel("Definition").selectOption(String(j.buildDefinitionId));await trigger(page,live,rows,"pointer","importedPolicyEffect");const combatBefore=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family:"combat",source:"pointer",beforeObservation:rows.filter(x=>x.kind==="observation").at(-1)?.value??null});await live.locator(refSelector("unit",j.combatTarget)).click();await settled(rows,combatBefore);const before=rows.filter(x=>x.kind==="submit").length;rows.push({kind:"action",family:"zeroWriteRefusal",source:"pointer",noSubmit:true,beforeObservation:rows.filter(x=>x.kind==="observation").at(-1)?.value??null});await live.getByLabel("Action").selectOption(j.unavailableAction??"setRally");await live.getByRole("button",{name:"Send tactical command"}).click({force:true});await page.waitForTimeout(250);expect(rows.filter(x=>x.kind==="submit")).toHaveLength(before)}
test.describe("actual tactical BAR receiver",()=>{test.skip(!enabled,"requires parent-owned tactical native handoff");for(const product of handoff?.products??[])for(const journey of product.journeys)test(`${product.id} ${journey.mode} reaches fenced tactical effects`,async({page})=>{const rows=await capture(page);if(journey.mode==="pointer")await exerciseManual(page,journey,rows,"pointer");else if(journey.mode==="keyboard")await exerciseManual(page,journey,rows,"keyboard");else await imported(page,journey,rows);const planned=[];let active=null,remaining=0,ordinal=0;for(const row of rows){if(row.kind==="action"&&!row.noSubmit){active=row;remaining=row.submitCount??1;ordinal=0}else if(row.kind==="submit"){planned.push({submit:row.value,family:active?.family,ordinal:ordinal++});if(--remaining<=0)active=null}}const parents=planned.map(({submit,family,ordinal})=>({id:submit.parentId,childCount:plannedChildCount(submit.intent),requireApplied:!["rejectBusy","mixedChildren"].includes(family)&&(family!=="staleRevision"||ordinal===0),requireNonApplied:family==="rejectBusy"||(family==="staleRevision"&&ordinal===1),requireMixed:family==="mixedChildren"})),stages={LIVE_RESULT_STAGE_BROKER_ADMISSION:"BrokerAdmission",LIVE_RESULT_STAGE_NATIVE_ADMISSION:"NativeAdmission",LIVE_RESULT_STAGE_NATIVE_DISPATCH:"NativeDispatch",LIVE_RESULT_STAGE_UNKNOWN:"Unknown"},statuses={LIVE_RESULT_STATUS_ACCEPTED:"Accepted",LIVE_RESULT_STATUS_REJECTED:"Rejected",LIVE_RESULT_STATUS_APPLIED:"Applied",LIVE_RESULT_STATUS_SKIPPED:"Skipped",LIVE_RESULT_STATUS_EXPIRED:"Expired",LIVE_RESULT_STATUS_UNKNOWN:"Unknown"},results=rows.filter(x=>x.kind==="result").map(x=>({kind:"result",parentId:x.value.parentId,childIndex:x.value.childIndex,childCount:x.value.childCount,stage:stages[x.value.stage],status:statuses[x.value.status]}));assertCanonicalLifecycle(results,parents);assertObservedEffects(rows,journey);await writeFile(journey.outputPath,rows.map(row=>JSON.stringify(row)).join("\n")+"\n",{mode:0o600,flag:"wx"})})});
