import test from "node:test";
import assert from "node:assert/strict";
import { assertCanonicalLifecycle, assertFactoryProductionEvidence, assertStockQueueEvidence, causalActionWindow, exactHealthDecreased, exactObservedUnit, isExactStaleBasisRefusal, isFreshPhysicalReplacement, newlyCompletedUnits, pendingRequiredCoverage, plannedChildCount, requiredManualFamilies, sanitizedLifecycle, validateTacticalHandoff, waitForTerminalOrClose } from "./tactical-native-evidence.mjs";

const ref=(id,lifetime="9007199254740993")=>({id:String(id),lifetime}),pos={build:{x:100,z:200},rally:{x:300,z:400},reclaim:{x:500,z:600}};
const journey=(product,mode)=>({id:`${product}-${mode}`,mode,receiverUrl:`http://127.0.0.1:3800/barc/?barc-profile=barc-live-tactical-v1`,allowedOrigin:"http://127.0.0.1:3800",gatewayUrl:"ws://127.0.0.1:3900/barc-live",expectedSessionId:"33221100-5544-7766-8899-aabbccddeeff",credential:`secret-${product}-${mode}`,nativeTracePath:"/private/native.jsonl",engineTracePath:"/private/engine.log",outputPath:`/private/${product}-${mode}.jsonl`,builder:ref(0),repairTarget:ref(1),reclaimUnitTarget:ref(4),factory:ref(2),combatTarget:ref(3),feature:ref(0,"9007199254740995"),areaFeature:ref(5,"9007199254740997"),mixedActors:[ref(0),ref(6)],mixedAppliedActor:ref(0),mixedRefusedActor:ref(6),mixedAction:"guard",modeActors:{constructionPriority:ref(0),cloakDesire:ref(6)},buildDefinitionId:710,productDefinitionId:711,existingProductionDefinitionId:712,productionCount:2,positions:pos,steps:(mode==="importedGuest"?["importedPolicyEffect","zeroWriteRefusal"]:requiredManualFamilies).map(family=>({family})),...(mode==="keyboard"?{keyboardTargets:"t/f/l-v1"}:{}),...(mode==="importedGuest"?{guestPath:"/private/custom.wasm",guestSha256:"a".repeat(64),importedExpectedAction:"build",importedActors:[ref(0)]}:{})});
const handoff=()=>({schema:"fsbar.barc-tactical-native-browser-handoff/v1",fixtureMode:false,sourceCommit:"b".repeat(40),archiveSha256:"c".repeat(64),clientSha256:"d".repeat(64),pluginSha256:"e".repeat(64),engineSha256:"f".repeat(64),profile:"barc-live-tactical-v1",protocolVersion:2,tacticalRevision:1,guestAbiVersion:1,codecDirectory:"/receiver/generated",requiredCoverageGaps:[...pendingRequiredCoverage],products:["local","generated"].map(id=>({id,receiverRoot:`/${id}`,journeys:["pointer","keyboard","importedGuest"].map(mode=>journey(id,mode))}))});

test("six-journey handoff pins exact roles, keyboard controls and imported bytes",()=>{const value=handoff();assert.equal(validateTacticalHandoff(value),value);const bad=structuredClone(value);bad.products[0].journeys[1].keyboardTargets="pointer-assisted";assert.throws(()=>validateTacticalHandoff(bad),/keyboard target-control/)});
test("handoff distinguishes required nonempty AppendN from pending positive Replace",()=>{const value=handoff();assert.deepEqual(value.requiredCoverageGaps,["factoryReplaceNonemptyPositive"]);assert(requiredManualFamilies.includes("factoryAppendQuantity"));assert(requiredManualFamilies.includes("factoryReplaceNonemptySafety"));assert(!requiredManualFamilies.includes("factoryCount"));const countOne=structuredClone(value);countOne.products[0].journeys[0].productionCount=1;assert.throws(()=>validateTacticalHandoff(countOne),/nonempty AppendN/);const noGap=structuredClone(value);noGap.requiredCoverageGaps=[];assert.throws(()=>validateTacticalHandoff(noGap),/pending native dependency/)});
test("every child needs a terminal outcome and mixed means native child divergence",()=>{const rows=[];for(let childIndex=0;childIndex<2;childIndex++)for(const[stage,status]of[["BrokerAdmission","Accepted"],["NativeAdmission",childIndex?"Rejected":"Accepted"],["NativeDispatch",childIndex?"Skipped":"Applied"]])rows.push({kind:"result",parentId:"p",childIndex,childCount:2,stage,status});assert.equal(assertCanonicalLifecycle(rows,[{id:"p",childCount:2,requireMixed:true}]),true);assert.throws(()=>assertCanonicalLifecycle(rows.filter(x=>x.stage!=="NativeDispatch"),[{id:"p",childCount:2}]),/terminal outcome/)});
test("factory fanout uses actor count times requested count and missing children fail",()=>{assert.equal(plannedChildCount({actors:[ref(0),ref(1)],factoryProduce:{count:3}}),6);assert.throws(()=>assertCanonicalLifecycle([{kind:"result",parentId:"p",childIndex:0,childCount:2,stage:"BrokerAdmission",status:"Rejected"}],[{id:"p",childCount:2}]),/child 1/)});
test("terminal wait distinguishes feedback, refusal, forwarded timeout and pre-terminal close",async()=>{for(const value of [{parentId:"p",childIndex:0,stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",status:"LIVE_RESULT_STATUS_APPLIED"},{parentId:"p",childIndex:0,stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",status:"LIVE_RESULT_STATUS_REJECTED"},{parentId:"p",childIndex:0,stage:"LIVE_RESULT_STAGE_UNKNOWN",status:"LIVE_RESULT_STATUS_EXPIRED"}])assert.equal(await waitForTerminalOrClose([{kind:"result",value}],{closed:false,error:false},"p",1,{timeoutMs:10}),1);await assert.rejects(waitForTerminalOrClose([],{closed:true,error:false},"p",1,{timeoutMs:1000}),/closed before terminal/);await assert.rejects(waitForTerminalOrClose([],{closed:false,error:false},"p",1,{timeoutMs:5,intervalMs:1}),/timed out/)});
test("partial lifecycle is fixed counts only",()=>{const privateValue="credential-uuid-coordinate";const summary=sanitizedLifecycle([{kind:"submit",value:{parentId:privateValue}},{kind:"result",value:{stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",detail:privateValue}}],{closed:true,error:true}),json=JSON.stringify(summary);assert.equal(summary.submitCount,1);assert.equal(summary.brokerAdmissionCount,1);assert.equal(summary.socketClosed,true);assert.equal(json.includes(privateValue),false)});

test("only an exact correlated tactical stale-basis refusal permits one explicit refresh",()=>{const submit={parentId:"p",basis:{stateSequence:"9",token:"basis"},intent:{actors:[ref(0)]}},value={parentId:"p",basis:submit.basis,childIndex:0,childCount:1,stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",status:"LIVE_RESULT_STATUS_REJECTED",disposition:"LIVE_RESULT_DISPOSITION_RECORDED",reason:"broker refused stale tactical observation basis; refresh the current observation"},rows=[{kind:"result",value}];assert.equal(isExactStaleBasisRefusal(rows,submit),true);for(const change of [{reason:"other refusal"},{stage:"LIVE_RESULT_STAGE_NATIVE_ADMISSION"},{status:"LIVE_RESULT_STATUS_ACCEPTED"},{disposition:"LIVE_RESULT_DISPOSITION_LATE"},{basis:{...submit.basis,stateSequence:"10"}},{parentId:"other"}])assert.equal(isExactStaleBasisRefusal([{kind:"result",value:{...value,...change}}],submit),false);const two={...submit,intent:{actors:[ref(0),ref(1)]}},mixed=[{kind:"result",value:{...value,childCount:2}},{kind:"result",value:{...value,childCount:2,childIndex:1,status:"LIVE_RESULT_STATUS_ACCEPTED"}}];assert.equal(isExactStaleBasisRefusal(mixed,two),false)});
test("fresh correction requires a captured newer basis and new physical parent and input identities",()=>{const stale={parentId:"old-parent",inputId:"old-input",controller:{authorityEpoch:"2"},module:{generation:"4"},basis:basis(9),intent:{action:"build",actors:[ref(0)]}},fresh={...stale,parentId:"new-parent",inputId:"new-input",basis:basis(10)};assert.equal(isFreshPhysicalReplacement(stale,fresh,[{basis:basis(10)}]),true);for(const change of [{parentId:stale.parentId},{inputId:stale.inputId},{controller:{authorityEpoch:"3"}},{module:{generation:"5"}},{basis:basis(9)},{basis:basis(10,"foreign")}])assert.equal(isFreshPhysicalReplacement(stale,{...fresh,...change},[{basis:{...fresh.basis,...change.basis}}]),false);assert.equal(isFreshPhysicalReplacement(stale,fresh,[]),false)});

const basis=(sequence,source="match")=>({matchId:source,processIncarnation:"process",stateChannelIncarnation:"channel",stateSequence:String(sequence),nativeFrame:Number(sequence)});
const liveUnit=(reference,definitionId,health,maxHealth=health)=>({reference,observation:"OBSERVATION_KIND_OWN",definitionId,health,maxHealth});
const observation=(sequence,units,source="match")=>({basis:basis(sequence,source),units:units.map(x=>({reference:x.reference,observation:x.observation})),preview:{units:units.map(x=>({id:x.reference.id,definitionId:x.definitionId,health:x.health,maxHealth:x.maxHealth,position:{x:1,z:2}}))}});
const productionEntry=(definitionId,nativeTag)=>({action:"LIVE_ACTION_KIND_FACTORY_PRODUCE",definitionId,nativeTag:String(nativeTag)});
const factoryObservation=(sequence,units,entries,revision="1")=>{const value=observation(sequence,units);value.tactical={actors:[{actor:ref(2),queue:[{domain:"QUEUE_DOMAIN_FACTORY_PRODUCTION",complete:true,revision,repeat:false,entries},{domain:"QUEUE_DOMAIN_FACTORY_RALLY",complete:true,revision:"rally-9",entries:[{action:"LIVE_ACTION_KIND_MOVE",position:{x:300,z:400}}]}]}]};return value};
const result=(parentId,childIndex,stage,status,basisValue,nativeFrame)=>({kind:"result",value:{parentId,childIndex,childCount:2,stage,status,disposition:"LIVE_RESULT_DISPOSITION_RECORDED",basis:basisValue,...(nativeFrame===undefined?{}:{nativeFrame})}});
const factoryEvidence=()=>{const old=productionEntry(712,41),first=productionEntry(711,42),second=productionEntry(711,43),appendBefore=factoryObservation(1,[],[old]),appendSubmit={parentId:"append",basis:basis(1),intent:{action:"factoryProduce",actors:[ref(2)],factoryProduce:{definitionId:711,count:2,queuePolicy:"TACTICAL_QUEUE_POLICY_APPEND"}}},queueAfter=factoryObservation(3,[],[old,first,second],"2"),products=[liveUnit(ref(20,"2"),711,10),liveUnit(ref(21,"3"),711,10)],productsAfter=factoryObservation(4,products,[],"3"),replaceBefore=factoryObservation(5,products,[productionEntry(712,44)],"4"),replaceSubmit={parentId:"replace",basis:basis(5),intent:{action:"factoryProduce",actors:[ref(2)],factoryProduce:{definitionId:711,count:2,queuePolicy:"TACTICAL_QUEUE_POLICY_REPLACE"}}},replaceAfter=factoryObservation(6,products,[productionEntry(712,44)],"4");return[{kind:"action",family:"factoryAppendQuantity",beforeObservation:appendBefore},{kind:"submit",value:appendSubmit},...Array.from({length:2},(_,child)=>[["LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"],["LIVE_RESULT_STAGE_NATIVE_ADMISSION","LIVE_RESULT_STATUS_ACCEPTED"],["LIVE_RESULT_STAGE_NATIVE_DISPATCH","LIVE_RESULT_STATUS_APPLIED"]].map(([stage,status])=>result("append",child,stage,status,basis(1),2))).flat(),{kind:"observation",value:queueAfter},{kind:"observation",value:productsAfter},{kind:"action",family:"factoryReplaceNonemptySafety",beforeObservation:replaceBefore},{kind:"submit",value:replaceSubmit},result("replace",0,"LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_REJECTED",basis(5)),result("replace",1,"LIVE_RESULT_STAGE_BROKER_ADMISSION","LIVE_RESULT_STATUS_REJECTED",basis(5)),{kind:"observation",value:replaceAfter}]};
test("factory oracle requires nonempty ordered AppendN and reports positive Replace pending",()=>{const value=journey("local","pointer"),verdict=assertFactoryProductionEvidence(factoryEvidence(),value);assert.deepEqual(verdict,{factoryAppendNonemptyQuantity:"observed",factoryReplaceNonemptySafety:"observed-refusal",factoryReplaceNonemptyPositive:"pending-native-dependency"})});
test("empty Count1, reordered Append, changed state, missing children and applied Replace cannot satisfy factory coverage",()=>{const value=journey("local","pointer"),empty=factoryEvidence();empty[0].beforeObservation.tactical.actors[0].queue[0].entries=[];assert.throws(()=>assertFactoryProductionEvidence(empty,value),/complete nonempty/);const reordered=factoryEvidence(),queueRow=reordered.find(x=>x.kind==="observation"&&x.value.basis.stateSequence==="3");queueRow.value.tactical.actors[0].queue[0].entries.reverse();assert.throws(()=>assertFactoryProductionEvidence(reordered,value),/preserve the existing ordered queue/);const repeat=factoryEvidence();repeat[0].beforeObservation.tactical.actors[0].queue[0].repeat=true;assert.throws(()=>assertFactoryProductionEvidence(repeat,value),/Repeat=false/);const rally=factoryEvidence(),rallyRow=rally.find(x=>x.kind==="observation"&&x.value.basis.stateSequence==="3");rallyRow.value.tactical.actors[0].queue[1].revision="mutated";assert.throws(()=>assertFactoryProductionEvidence(rally,value),/preserve the existing ordered queue/);const missing=factoryEvidence().filter(x=>!(x.kind==="result"&&x.value.parentId==="append"&&x.value.childIndex===1));assert.throws(()=>assertFactoryProductionEvidence(missing,value),/child 1/);const applied=factoryEvidence(),refusal=applied.find(x=>x.kind==="result"&&x.value.parentId==="replace");refusal.value.stage="LIVE_RESULT_STAGE_NATIVE_DISPATCH";refusal.value.status="LIVE_RESULT_STATUS_APPLIED";assert.throws(()=>assertFactoryProductionEvidence(applied,value),/correlated broker refusal/)});
const stockExpected=()=>({profile:"barc-live-tactical-stock-v1",tacticalRevision:2,queueEvidenceScheme:2,queueBridge:"barc-stock-queue-reader-v1",supportedQueueFields:["domain","id","options.coded","tag","float32params"],actor:ref(2)});
const stockEvidence=()=>{
  const append={parentId:"stock-append",intent:{action:"factoryProduce",actors:[ref(2)],factoryProduce:{definitionId:711,count:2,queuePolicy:"TACTICAL_QUEUE_POLICY_APPEND"}}};
  const replace={parentId:"stock-replace",intent:{action:"factoryProduce",actors:[ref(2)],factoryProduce:{definitionId:711,count:2,queuePolicy:"TACTICAL_QUEUE_POLICY_REPLACE"}}};
  const results=[];
  for(let childIndex=0;childIndex<2;childIndex++){
    results.push({kind:"result",value:{parentId:append.parentId,childIndex,childCount:2,stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",status:"LIVE_RESULT_STATUS_APPLIED"}});
    results.push({kind:"result",value:{parentId:replace.parentId,childIndex,childCount:2,stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION",status:"LIVE_RESULT_STATUS_REJECTED"}});
  }
  return [
    {kind:"stockQueueEvidence",value:{...stockExpected(),domain:"QUEUE_DOMAIN_FACTORY_PRODUCTION",queueRevision:"9007199254742001",timeout:"unavailable",basis:basis(20),entries:[{id:-711,codedOptions:32,tag:41,float32params:["3f800000","80000000"]}]}},
    {kind:"submit",value:append},{kind:"submit",value:replace},...results
  ];
};
test("stock queue oracle binds supported raw fields, lifetime, revisions and actual per-child results",()=>{
  assert.deepEqual(assertStockQueueEvidence(stockEvidence(),stockExpected()),{schema:"fsbar.barc-stock-tactical-oracle/v1",profile:"barc-live-tactical-stock-v1",tacticalRevision:2,queueEvidenceScheme:2,queueBridge:"barc-stock-queue-reader-v1",supportedQueueFields:["domain","id","options.coded","tag","float32params"],timeout:"unavailable",actorLifetime:"observed",currentTag:"observed",supportedFieldFreshness:"basis-and-queue-revision-observed",appliedChildCount:2,factoryReplace:"broker-refused",rollback:"unknown",peerService:"unknown"});
});
test("stock queue oracle refuses timeout fabrication, cross-scheme rows, lossy bits and incomplete child evidence",()=>{
  const timeout=stockEvidence();timeout[0].value.timeout="0";assert.throws(()=>assertStockQueueEvidence(timeout,stockExpected()),/claimed timeout/);
  const scheme=stockEvidence();scheme[0].value.queueEvidenceScheme=1;assert.throws(()=>assertStockQueueEvidence(scheme,stockExpected()),/profile or evidence scheme/);
  const bits=stockEvidence();bits[0].value.entries[0].float32params[1]="8000000A";assert.throws(()=>assertStockQueueEvidence(bits,stockExpected()),/lowercase binary32/);
  const missing=stockEvidence().filter(row=>!(row.kind==="result"&&row.value.parentId==="stock-append"&&row.value.childIndex===1));assert.throws(()=>assertStockQueueEvidence(missing,stockExpected()),/child 1/);
  const nativeReplace=stockEvidence();const refused=nativeReplace.find(row=>row.kind==="result"&&row.value.parentId==="stock-replace");refused.value.stage="LIVE_RESULT_STAGE_NATIVE_DISPATCH";refused.value.status="LIVE_RESULT_STATUS_APPLIED";assert.throws(()=>assertStockQueueEvidence(nativeReplace,stockExpected()),/per-child broker refusal/);
});
test("causal window excludes foreign source and later unrelated effects",()=>{const before=observation(1,[liveUnit(ref(1),10,10)]),foreign=observation(3,[liveUnit(ref(2),710,10)],"other"),later=observation(9,[liveUnit(ref(3),710,10)]),rows=[{kind:"action",family:"construction",beforeObservation:before},{kind:"submit",value:{parentId:"p",basis:basis(1)}},{kind:"result",value:{parentId:"p",stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",nativeFrame:2}},{kind:"observation",value:foreign},{kind:"action",family:"next",beforeObservation:foreign},{kind:"observation",value:later}];assert.throws(()=>causalActionWindow(rows,"construction"),/bounded later same-source/)});
test("causal window binds effects to the fresh parent after a recorded stale-basis refusal",()=>{const before=observation(1,[liveUnit(ref(1),10,10)]),after=observation(3,[liveUnit(ref(2),710,10)]),rows=[{kind:"action",family:"construction",beforeObservation:before,causalSubmitOrdinal:1},{kind:"submit",value:{parentId:"stale",basis:basis(1)}},{kind:"result",value:{parentId:"stale",stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION"}},{kind:"submit",value:{parentId:"fresh",basis:basis(2)}},{kind:"result",value:{parentId:"fresh",stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",nativeFrame:2}},{kind:"observation",value:after}];assert.equal(causalActionWindow(rows,"construction").submit.parentId,"fresh")});
test("change between refused and fresh inputs is the refreshed baseline, not a fresh-action effect",()=>{const initial=observation(1,[liveUnit(ref(1),10,10)]),intervening=observation(2,[liveUnit(ref(1),10,10),liveUnit(ref(2),710,10)]),unchanged=observation(4,[liveUnit(ref(1),10,10),liveUnit(ref(2),710,10)]),action={kind:"action",family:"construction",beforeObservation:intervening,observationCount:2,causalSubmitOrdinal:1,staleBasisRefresh:{originalBeforeObservation:initial,originalObservationCount:1}},rows=[action,{kind:"submit",value:{parentId:"stale",basis:basis(1)}},{kind:"result",value:{parentId:"stale",stage:"LIVE_RESULT_STAGE_BROKER_ADMISSION"}},{kind:"observation",value:intervening},{kind:"submit",value:{parentId:"fresh",basis:basis(2)}},{kind:"result",value:{parentId:"fresh",stage:"LIVE_RESULT_STAGE_NATIVE_DISPATCH",nativeFrame:3}},{kind:"observation",value:unchanged}];const window=causalActionWindow(rows,"construction");assert.equal(window.before,intervening);assert.equal(newlyCompletedUnits(window.before,window.last,710).length,0)});
test("unit evidence binds lifetime and rejects preexisting or wrong causal type",()=>{const old=ref(7,"1"),reused=ref(7,"2"),before=observation(1,[liveUnit(old,710,10)]),same=observation(2,[liveUnit(old,710,10)]),reuse=observation(3,[liveUnit(reused,710,10)]),damaged=observation(4,[liveUnit(reused,710,5,10)]);assert.equal(newlyCompletedUnits(before,same,710).length,0);assert.equal(newlyCompletedUnits(before,reuse,710).length,1);assert.equal(exactObservedUnit(reuse,old),undefined);assert.equal(exactObservedUnit(reuse,reused).health,10);assert.equal(exactHealthDecreased(reuse,damaged,reused),true);assert.equal(exactHealthDecreased(reuse,damaged,old),false)});
